package loc

import (
	"context"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/cgardev/goconduct/internal/library/goloc"
	"github.com/cgardev/goconduct/pkg/failure"
	"github.com/cgardev/goconduct/pkg/plugin"
	"github.com/cgardev/goconduct/pkg/policy"
)

type pathSelectorFunc func(repositoryPath string) (bool, error)

func (selector pathSelectorFunc) Select(repositoryPath string) (bool, error) {
	return selector(repositoryPath)
}

func locFixtureRoot(t *testing.T) string {
	t.Helper()
	return materializeFixture(t, "repository")
}

func materializeFixture(t *testing.T, name string) string {
	t.Helper()
	sourceRoot := filepath.Join("testdata", name)
	targetRoot := t.TempDir()
	err := filepath.WalkDir(sourceRoot, func(sourcePath string, entry fs.DirEntry, walkError error) error {
		if walkError != nil {
			return walkError
		}
		relative, err := filepath.Rel(sourceRoot, sourcePath)
		if err != nil {
			return err
		}
		targetPath := filepath.Join(targetRoot, relative)
		if entry.IsDir() {
			return os.MkdirAll(targetPath, 0o750)
		}
		if strings.HasSuffix(targetPath, ".gotxt") {
			targetPath = strings.TrimSuffix(targetPath, ".gotxt") + ".go"
		}
		payload, err := os.ReadFile(sourcePath)
		if err != nil {
			return err
		}
		return os.WriteFile(targetPath, payload, 0o600)
	})
	if err != nil {
		t.Fatalf("materialize fixture %q: %v", name, err)
	}
	return targetRoot
}

func fixtureConfiguration() Configuration {
	configuration := DefaultConfiguration()
	configuration.Selection.Exclude = append(
		configuration.Selection.Exclude,
		"internal/skip/**",
	)
	configuration.Generated.HeaderPatterns = []string{"(?m)^// AUTOGENERATED$"}
	configuration.Generated.ForceHandwrittenPaths = []string{"manual.pb.go"}
	return configuration
}

func reportMetric(
	t *testing.T,
	report plugin.Report,
	name string,
	repositoryPath string,
) plugin.Metric {
	t.Helper()
	for _, metric := range report.Metrics {
		if metric.Name == name && metric.Path == repositoryPath {
			return metric
		}
	}
	t.Fatalf("metric %q for %q is absent", name, repositoryPath)
	return plugin.Metric{}
}

func TestEvaluatorReportsRepositoryModulePackageFileAndFunctionMetrics(t *testing.T) {
	evaluator, err := NewEvaluator(fixtureConfiguration())
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}

	report, err := evaluator.Evaluate(t.Context(), plugin.Request{RepositoryRoot: locFixtureRoot(t)})
	if err != nil {
		t.Fatalf("evaluate LOC fixture: %v", err)
	}

	wants := map[string]float64{
		"loc.repository.files.total":         7,
		"loc.repository.files.test":          1,
		"loc.repository.files.generated":     3,
		"loc.repository.lines.total":         25,
		"loc.repository.lines.code":          16,
		"loc.repository.lines.comment":       3,
		"loc.repository.lines.blank":         6,
		"loc.repository.lines.test":          3,
		"loc.repository.lines.generated":     10,
		"loc.repository.functions.total":     7,
		"loc.repository.functions.test":      1,
		"loc.repository.functions.generated": 3,
	}
	for name, want := range wants {
		if got := reportMetric(t, report, name, "").Value; got != want {
			t.Errorf("metric %s is %.2f, want %.2f", name, got, want)
		}
	}
	if got := reportMetric(t, report, "loc.module.functions.total", "go.mod").Value; got != 6 {
		t.Errorf("the root module reports %.2f functions, want 6", got)
	}
	if got := reportMetric(t, report, "loc.module.functions.total", "tools/go.mod").Value; got != 1 {
		t.Errorf("the nested module reports %.2f functions, want 1", got)
	}
	if got := reportMetric(t, report, "loc.package.functions.total", "internal/protogen").Value; got != 1 {
		t.Errorf("the protobuf package reports %.2f functions, want 1", got)
	}
	if got := reportMetric(t, report, "loc.file.files.generated", "manual.pb.go").Value; got != 0 {
		t.Errorf("the manual override reports %.2f generated files, want 0", got)
	}
	if got := reportMetric(t, report, "loc.file.files.generated", "generated/custom.go").Value; got != 1 {
		t.Errorf("the custom marker reports %.2f generated files, want 1", got)
	}
	if got := reportMetric(t, report, "loc.file.files.generated", "internal/protogen/message.pb.go").Value; got != 1 {
		t.Errorf("the protobuf path reports %.2f generated files, want 1", got)
	}
	if got := reportMetric(t, report, "loc.function.lines.code", "main.go").Value; got != 3 {
		t.Errorf("the Main function reports %.2f code lines, want 3", got)
	}
	for _, metric := range report.Metrics {
		if strings.Contains(metric.Path, "internal/skip") || strings.Contains(metric.Path, "fixtures/testdata") {
			t.Errorf("excluded path reached the report: %+v", metric)
		}
		if strings.HasPrefix(metric.Name, "loc.file.function-lines.") {
			t.Errorf("a file received aggregate function statistics: %+v", metric)
		}
	}
}

func TestGeneratedClassifierReturnsInvalidPathFailures(t *testing.T) {
	tests := []GeneratedConfiguration{
		{ForceHandwrittenPaths: []string{"**/*.go"}},
		{PathPatterns: []string{"**/*.go"}},
	}
	for _, configuration := range tests {
		classifier, err := newGeneratedClassifier(configuration)
		if err != nil {
			t.Fatalf("create generated classifier: %v", err)
		}

		generated, err := classifier.classify("../outside.go", goloc.File{})
		if generated {
			t.Error("the classifier marks an invalid path as generated")
		}

		if !errors.Is(err, failure.ErrValidation) {
			t.Errorf("the classifier reports %v, want a validation failure", err)
		}
	}
}

func TestMetricCalculationsHandleEmptyAndPopulatedSets(t *testing.T) {
	if got := percentage(4, 0); got != 0 {
		t.Errorf("percentage with no denominator is %.2f", got)
	}
	if got := percentage(1, 4); got != 25 {
		t.Errorf("percentage is %.2f, want 25", got)
	}
	average, percentile95, maximum := functionLineStatistics(nil)
	if average != 0 || percentile95 != 0 || maximum != 0 {
		t.Errorf("empty statistics are %.2f, %d, %d", average, percentile95, maximum)
	}
	average, percentile95, maximum = functionLineStatistics([]int{1, 3, 2})
	if average != 2 || percentile95 != 3 || maximum != 3 {
		t.Errorf("statistics are %.2f, %d, %d", average, percentile95, maximum)
	}
}

func TestEvaluatorAppliesRequestPathsBeforeConfiguredFilters(t *testing.T) {
	configuration := fixtureConfiguration()
	configuration.Selection.Paths = []string{"absent"}
	evaluator, err := NewEvaluator(configuration)
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}

	report, err := evaluator.Evaluate(t.Context(), plugin.Request{
		RepositoryRoot: locFixtureRoot(t),
		Paths:          []string{"internal/protogen"},
	})
	if err != nil {
		t.Fatalf("evaluate request path: %v", err)
	}

	if got := reportMetric(t, report, "loc.repository.files.total", "").Value; got != 1 {
		t.Errorf("the request path reports %.2f files, want 1", got)
	}
}

func TestEvaluatorAppliesIncludeAndExcludePatterns(t *testing.T) {
	configuration := fixtureConfiguration()
	configuration.Selection.Include = []string{"internal/**"}
	evaluator, err := NewEvaluator(configuration)
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}

	report, err := evaluator.Evaluate(t.Context(), plugin.Request{RepositoryRoot: locFixtureRoot(t)})
	if err != nil {
		t.Fatalf("evaluate selected paths: %v", err)
	}

	paths := make([]string, 0)
	for _, metric := range report.Metrics {
		if metric.Name == "loc.file.files.total" {
			paths = append(paths, metric.Path)
		}
	}
	if !slices.Equal(paths, []string{"internal/protogen/message.pb.go"}) {
		t.Errorf("the filtered files are %v", paths)
	}
}

func TestEvaluatorCreatesFindingsFromPathPolicies(t *testing.T) {
	configuration := fixtureConfiguration()
	configuration.Policies = []policy.PathPolicy{{
		ID:      "small-main-functions",
		Include: []string{"main.go"},
		Thresholds: []policy.Threshold{{
			Metric: "loc.function.lines.code", Comparison: policy.ComparisonMaximum,
			Value: 2, Severity: plugin.SeverityError,
		}},
	}}
	evaluator, err := NewEvaluator(configuration)
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}

	report, err := evaluator.Evaluate(t.Context(), plugin.Request{RepositoryRoot: locFixtureRoot(t)})
	if err != nil {
		t.Fatalf("evaluate LOC policy: %v", err)
	}

	if len(report.Findings) != 1 {
		t.Fatalf("the policy reports %d findings, want 1", len(report.Findings))
	}
	finding := report.Findings[0]
	if finding.Path != "main.go" || finding.Actual == nil || *finding.Actual != 3 ||
		finding.Limit == nil || *finding.Limit != 2 {
		t.Errorf("the policy finding is %+v", finding)
	}
}

func TestEvaluatorRejectsInvalidRootsModulesAndSources(t *testing.T) {
	evaluator, err := NewEvaluator(DefaultConfiguration())
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}
	if _, err := evaluator.Evaluate(t.Context(), plugin.Request{
		RepositoryRoot: locFixtureRoot(t), Paths: []string{"absent"},
	}); !errors.Is(err, failure.ErrValidation) {
		t.Errorf("the absent root reports %v, want a validation failure", err)
	}
	if _, err := evaluator.Evaluate(t.Context(), plugin.Request{
		RepositoryRoot: materializeFixture(t, "without-module"),
	}); !errors.Is(err, failure.ErrValidation) {
		t.Errorf("the missing module reports %v, want a validation failure", err)
	}
	if _, err := evaluator.Evaluate(t.Context(), plugin.Request{
		RepositoryRoot: materializeFixture(t, "invalid-source"),
	}); !errors.Is(err, failure.ErrDataIntegrity) {
		t.Errorf("the invalid source reports %v, want a data integrity failure", err)
	}
}

func TestEvaluatorStopsWhenTheContextIsCancelled(t *testing.T) {
	evaluator, err := NewEvaluator(fixtureConfiguration())
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()

	_, err = evaluator.Evaluate(ctx, plugin.Request{RepositoryRoot: locFixtureRoot(t)})

	if !errors.Is(err, context.Canceled) {
		t.Errorf("the cancelled analysis reports %v, want context cancellation", err)
	}
}

func TestEvaluatorReportsAnUnavailableWorkingDirectory(t *testing.T) {
	evaluator, err := NewEvaluator(DefaultConfiguration())
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}
	originalDirectory, err := os.Getwd()
	if err != nil {
		t.Fatalf("read the working directory: %v", err)
	}
	removedDirectory := t.TempDir()
	if err := os.Chdir(removedDirectory); err != nil {
		t.Fatalf("change the working directory: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(originalDirectory); err != nil {
			t.Errorf("restore the working directory: %v", err)
		}
	})
	if err := os.Remove(removedDirectory); err != nil {
		t.Fatalf("remove the working directory: %v", err)
	}

	_, err = evaluator.Evaluate(t.Context(), plugin.Request{})

	if !errors.Is(err, failure.ErrInternal) {
		t.Errorf("the missing working directory reports %v, want an internal failure", err)
	}
}

func TestEvaluatorRejectsAmbiguousPolicies(t *testing.T) {
	threshold := policy.Threshold{
		Metric: "loc.file.files.total", Comparison: policy.ComparisonMaximum,
		Value: 0, Severity: plugin.SeverityError,
	}
	configuration := DefaultConfiguration()
	configuration.Selection.Paths = []string{"main.go"}
	configuration.Policies = []policy.PathPolicy{
		{ID: "first", Include: []string{"main.go"}, Thresholds: []policy.Threshold{threshold}},
		{ID: "second", Include: []string{"main.go"}, Thresholds: []policy.Threshold{threshold}},
	}
	evaluator, err := NewEvaluator(configuration)
	if err != nil {
		t.Fatalf("create LOC evaluator: %v", err)
	}

	_, err = evaluator.Evaluate(t.Context(), plugin.Request{RepositoryRoot: locFixtureRoot(t)})

	if !errors.Is(err, failure.ErrValidation) {
		t.Errorf("the ambiguous policies report %v, want a validation failure", err)
	}
}

func TestMeasureFilesReturnsSelectionAndClassificationFailures(t *testing.T) {
	t.Run("a selection failure", func(t *testing.T) {
		evaluator, err := NewEvaluator(DefaultConfiguration())
		if err != nil {
			t.Fatalf("create LOC evaluator: %v", err)
		}
		evaluator.selector = pathSelectorFunc(func(string) (bool, error) {
			return false, failure.Validation("select source path", nil)
		})

		_, err = evaluator.measureFiles(t.Context(), t.TempDir(), []string{"sample.go"})

		if !errors.Is(err, failure.ErrValidation) {
			t.Errorf("the selector reports %v, want a validation failure", err)
		}
	})

	t.Run("a generated classification failure", func(t *testing.T) {
		configuration := DefaultConfiguration()
		configuration.Generated.ForceHandwrittenPaths = []string{"**/*.go"}
		evaluator, err := NewEvaluator(configuration)
		if err != nil {
			t.Fatalf("create LOC evaluator: %v", err)
		}
		evaluator.selector = pathSelectorFunc(func(string) (bool, error) { return true, nil })
		parentDirectory := t.TempDir()
		repositoryRoot := filepath.Join(parentDirectory, "repository")
		if err := os.Mkdir(repositoryRoot, 0o750); err != nil {
			t.Fatalf("create repository root: %v", err)
		}
		source, err := os.ReadFile(filepath.Join("testdata", "repository", "main.gotxt"))
		if err != nil {
			t.Fatalf("read source fixture: %v", err)
		}
		if err := os.WriteFile(filepath.Join(parentDirectory, "outside.go"), source, 0o600); err != nil {
			t.Fatalf("write temporary source: %v", err)
		}

		_, err = evaluator.measureFiles(t.Context(), repositoryRoot, []string{"../outside.go"})

		if !errors.Is(err, failure.ErrValidation) {
			t.Errorf("the classifier reports %v, want a validation failure", err)
		}
	})
}

func TestLocateModuleRejectsInvalidAndUnreadableModuleFiles(t *testing.T) {
	t.Run("a missing module path", func(t *testing.T) {
		repositoryRoot := t.TempDir()
		if err := os.WriteFile(filepath.Join(repositoryRoot, "go.mod"), []byte("go 1.26\n"), 0o600); err != nil {
			t.Fatalf("write module file: %v", err)
		}

		_, err := locateModule(repositoryRoot, "sample.go", make(map[string]moduleDescriptor))

		if !errors.Is(err, failure.ErrDataIntegrity) {
			t.Errorf("the missing module path reports %v, want a data integrity failure", err)
		}
	})

	t.Run("an unreadable module file", func(t *testing.T) {
		repositoryRoot := t.TempDir()
		if err := os.Mkdir(filepath.Join(repositoryRoot, "go.mod"), 0o750); err != nil {
			t.Fatalf("create module directory: %v", err)
		}

		_, err := locateModule(repositoryRoot, "sample.go", make(map[string]moduleDescriptor))

		if !errors.Is(err, failure.ErrUnavailable) {
			t.Errorf("the unreadable module reports %v, want an unavailable failure", err)
		}
	})
}
