// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/graph.proto

package goconductv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cgardev/goconduct/internal/protogen/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GraphServiceName is the fully-qualified name of the GraphService service.
	GraphServiceName = "goconduct.v1.GraphService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GraphServiceGetGraphProcedure is the fully-qualified name of the GraphService's GetGraph RPC.
	GraphServiceGetGraphProcedure = "/goconduct.v1.GraphService/GetGraph"
	// GraphServiceWatchGraphProcedure is the fully-qualified name of the GraphService's WatchGraph RPC.
	GraphServiceWatchGraphProcedure = "/goconduct.v1.GraphService/WatchGraph"
)

// GraphServiceClient is a client for the goconduct.v1.GraphService service.
type GraphServiceClient interface {
	// GetGraph returns the complete active dependency graph.
	GetGraph(context.Context, *connect.Request[v1.GetGraphRequest]) (*connect.Response[v1.GetGraphResponse], error)
	// WatchGraph reports graph revisions while the dashboard remains open.
	WatchGraph(context.Context, *connect.Request[v1.WatchGraphRequest]) (*connect.ServerStreamForClient[v1.WatchGraphResponse], error)
}

// NewGraphServiceClient constructs a client for the goconduct.v1.GraphService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGraphServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GraphServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	graphServiceMethods := v1.File_v1_graph_proto.Services().ByName("GraphService").Methods()
	return &graphServiceClient{
		getGraph: connect.NewClient[v1.GetGraphRequest, v1.GetGraphResponse](
			httpClient,
			baseURL+GraphServiceGetGraphProcedure,
			connect.WithSchema(graphServiceMethods.ByName("GetGraph")),
			connect.WithClientOptions(opts...),
		),
		watchGraph: connect.NewClient[v1.WatchGraphRequest, v1.WatchGraphResponse](
			httpClient,
			baseURL+GraphServiceWatchGraphProcedure,
			connect.WithSchema(graphServiceMethods.ByName("WatchGraph")),
			connect.WithClientOptions(opts...),
		),
	}
}

// graphServiceClient implements GraphServiceClient.
type graphServiceClient struct {
	getGraph   *connect.Client[v1.GetGraphRequest, v1.GetGraphResponse]
	watchGraph *connect.Client[v1.WatchGraphRequest, v1.WatchGraphResponse]
}

// GetGraph calls goconduct.v1.GraphService.GetGraph.
func (c *graphServiceClient) GetGraph(ctx context.Context, req *connect.Request[v1.GetGraphRequest]) (*connect.Response[v1.GetGraphResponse], error) {
	return c.getGraph.CallUnary(ctx, req)
}

// WatchGraph calls goconduct.v1.GraphService.WatchGraph.
func (c *graphServiceClient) WatchGraph(ctx context.Context, req *connect.Request[v1.WatchGraphRequest]) (*connect.ServerStreamForClient[v1.WatchGraphResponse], error) {
	return c.watchGraph.CallServerStream(ctx, req)
}

// GraphServiceHandler is an implementation of the goconduct.v1.GraphService service.
type GraphServiceHandler interface {
	// GetGraph returns the complete active dependency graph.
	GetGraph(context.Context, *connect.Request[v1.GetGraphRequest]) (*connect.Response[v1.GetGraphResponse], error)
	// WatchGraph reports graph revisions while the dashboard remains open.
	WatchGraph(context.Context, *connect.Request[v1.WatchGraphRequest], *connect.ServerStream[v1.WatchGraphResponse]) error
}

// NewGraphServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGraphServiceHandler(svc GraphServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	graphServiceMethods := v1.File_v1_graph_proto.Services().ByName("GraphService").Methods()
	graphServiceGetGraphHandler := connect.NewUnaryHandler(
		GraphServiceGetGraphProcedure,
		svc.GetGraph,
		connect.WithSchema(graphServiceMethods.ByName("GetGraph")),
		connect.WithHandlerOptions(opts...),
	)
	graphServiceWatchGraphHandler := connect.NewServerStreamHandler(
		GraphServiceWatchGraphProcedure,
		svc.WatchGraph,
		connect.WithSchema(graphServiceMethods.ByName("WatchGraph")),
		connect.WithHandlerOptions(opts...),
	)
	return "/goconduct.v1.GraphService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GraphServiceGetGraphProcedure:
			graphServiceGetGraphHandler.ServeHTTP(w, r)
		case GraphServiceWatchGraphProcedure:
			graphServiceWatchGraphHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGraphServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGraphServiceHandler struct{}

func (UnimplementedGraphServiceHandler) GetGraph(context.Context, *connect.Request[v1.GetGraphRequest]) (*connect.Response[v1.GetGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("goconduct.v1.GraphService.GetGraph is not implemented"))
}

func (UnimplementedGraphServiceHandler) WatchGraph(context.Context, *connect.Request[v1.WatchGraphRequest], *connect.ServerStream[v1.WatchGraphResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("goconduct.v1.GraphService.WatchGraph is not implemented"))
}
