// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/quality.proto

package goconductv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cgardev/goconduct/internal/protogen/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QualityServiceName is the fully-qualified name of the QualityService service.
	QualityServiceName = "goconduct.v1.QualityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QualityServiceListPluginsProcedure is the fully-qualified name of the QualityService's
	// ListPlugins RPC.
	QualityServiceListPluginsProcedure = "/goconduct.v1.QualityService/ListPlugins"
	// QualityServiceRunCheckProcedure is the fully-qualified name of the QualityService's RunCheck RPC.
	QualityServiceRunCheckProcedure = "/goconduct.v1.QualityService/RunCheck"
)

// QualityServiceClient is a client for the goconduct.v1.QualityService service.
type QualityServiceClient interface {
	// ListPlugins returns every evaluator available in this binary.
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error)
	// RunCheck executes selected evaluators and returns their normalized evidence.
	RunCheck(context.Context, *connect.Request[v1.RunCheckRequest]) (*connect.Response[v1.RunCheckResponse], error)
}

// NewQualityServiceClient constructs a client for the goconduct.v1.QualityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQualityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QualityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	qualityServiceMethods := v1.File_v1_quality_proto.Services().ByName("QualityService").Methods()
	return &qualityServiceClient{
		listPlugins: connect.NewClient[v1.ListPluginsRequest, v1.ListPluginsResponse](
			httpClient,
			baseURL+QualityServiceListPluginsProcedure,
			connect.WithSchema(qualityServiceMethods.ByName("ListPlugins")),
			connect.WithClientOptions(opts...),
		),
		runCheck: connect.NewClient[v1.RunCheckRequest, v1.RunCheckResponse](
			httpClient,
			baseURL+QualityServiceRunCheckProcedure,
			connect.WithSchema(qualityServiceMethods.ByName("RunCheck")),
			connect.WithClientOptions(opts...),
		),
	}
}

// qualityServiceClient implements QualityServiceClient.
type qualityServiceClient struct {
	listPlugins *connect.Client[v1.ListPluginsRequest, v1.ListPluginsResponse]
	runCheck    *connect.Client[v1.RunCheckRequest, v1.RunCheckResponse]
}

// ListPlugins calls goconduct.v1.QualityService.ListPlugins.
func (c *qualityServiceClient) ListPlugins(ctx context.Context, req *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error) {
	return c.listPlugins.CallUnary(ctx, req)
}

// RunCheck calls goconduct.v1.QualityService.RunCheck.
func (c *qualityServiceClient) RunCheck(ctx context.Context, req *connect.Request[v1.RunCheckRequest]) (*connect.Response[v1.RunCheckResponse], error) {
	return c.runCheck.CallUnary(ctx, req)
}

// QualityServiceHandler is an implementation of the goconduct.v1.QualityService service.
type QualityServiceHandler interface {
	// ListPlugins returns every evaluator available in this binary.
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error)
	// RunCheck executes selected evaluators and returns their normalized evidence.
	RunCheck(context.Context, *connect.Request[v1.RunCheckRequest]) (*connect.Response[v1.RunCheckResponse], error)
}

// NewQualityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQualityServiceHandler(svc QualityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	qualityServiceMethods := v1.File_v1_quality_proto.Services().ByName("QualityService").Methods()
	qualityServiceListPluginsHandler := connect.NewUnaryHandler(
		QualityServiceListPluginsProcedure,
		svc.ListPlugins,
		connect.WithSchema(qualityServiceMethods.ByName("ListPlugins")),
		connect.WithHandlerOptions(opts...),
	)
	qualityServiceRunCheckHandler := connect.NewUnaryHandler(
		QualityServiceRunCheckProcedure,
		svc.RunCheck,
		connect.WithSchema(qualityServiceMethods.ByName("RunCheck")),
		connect.WithHandlerOptions(opts...),
	)
	return "/goconduct.v1.QualityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QualityServiceListPluginsProcedure:
			qualityServiceListPluginsHandler.ServeHTTP(w, r)
		case QualityServiceRunCheckProcedure:
			qualityServiceRunCheckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQualityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQualityServiceHandler struct{}

func (UnimplementedQualityServiceHandler) ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("goconduct.v1.QualityService.ListPlugins is not implemented"))
}

func (UnimplementedQualityServiceHandler) RunCheck(context.Context, *connect.Request[v1.RunCheckRequest]) (*connect.Response[v1.RunCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("goconduct.v1.QualityService.RunCheck is not implemented"))
}
