// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/graph.proto

package goconductv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GraphEventType identifies one event in the graph stream.
type GraphEventType int32

const (
	GraphEventType_GRAPH_EVENT_TYPE_UNSPECIFIED GraphEventType = 0
	GraphEventType_GRAPH_EVENT_TYPE_READY       GraphEventType = 1
	GraphEventType_GRAPH_EVENT_TYPE_CHANGED     GraphEventType = 2
	GraphEventType_GRAPH_EVENT_TYPE_HEARTBEAT   GraphEventType = 3
)

// Enum value maps for GraphEventType.
var (
	GraphEventType_name = map[int32]string{
		0: "GRAPH_EVENT_TYPE_UNSPECIFIED",
		1: "GRAPH_EVENT_TYPE_READY",
		2: "GRAPH_EVENT_TYPE_CHANGED",
		3: "GRAPH_EVENT_TYPE_HEARTBEAT",
	}
	GraphEventType_value = map[string]int32{
		"GRAPH_EVENT_TYPE_UNSPECIFIED": 0,
		"GRAPH_EVENT_TYPE_READY":       1,
		"GRAPH_EVENT_TYPE_CHANGED":     2,
		"GRAPH_EVENT_TYPE_HEARTBEAT":   3,
	}
)

func (x GraphEventType) Enum() *GraphEventType {
	p := new(GraphEventType)
	*p = x
	return p
}

func (x GraphEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_graph_proto_enumTypes[0].Descriptor()
}

func (GraphEventType) Type() protoreflect.EnumType {
	return &file_v1_graph_proto_enumTypes[0]
}

func (x GraphEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphEventType.Descriptor instead.
func (GraphEventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{0}
}

// GetGraphRequest controls cache validation and an optional immediate refresh.
type GetGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       bool                   `protobuf:"varint,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	CacheKey      string                 `protobuf:"bytes,2,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	CacheProtocol uint32                 `protobuf:"varint,3,opt,name=cache_protocol,json=cacheProtocol,proto3" json:"cache_protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GetGraphRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

func (x *GetGraphRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *GetGraphRequest) GetCacheProtocol() uint32 {
	if x != nil {
		return x.CacheProtocol
	}
	return 0
}

// GetGraphResponse carries the graph and its cache identity.
type GetGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	CacheKey      string                 `protobuf:"bytes,2,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	CacheProtocol uint32                 `protobuf:"varint,3,opt,name=cache_protocol,json=cacheProtocol,proto3" json:"cache_protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GetGraphResponse) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *GetGraphResponse) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *GetGraphResponse) GetCacheProtocol() uint32 {
	if x != nil {
		return x.CacheProtocol
	}
	return 0
}

// WatchGraphRequest identifies the latest revision known by the client.
type WatchGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRevision  string                 `protobuf:"bytes,1,opt,name=from_revision,json=fromRevision,proto3" json:"from_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGraphRequest) Reset() {
	*x = WatchGraphRequest{}
	mi := &file_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGraphRequest) ProtoMessage() {}

func (x *WatchGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGraphRequest.ProtoReflect.Descriptor instead.
func (*WatchGraphRequest) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *WatchGraphRequest) GetFromRevision() string {
	if x != nil {
		return x.FromRevision
	}
	return ""
}

// WatchGraphResponse reports one graph stream event.
type WatchGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GraphEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=goconduct.v1.GraphEventType" json:"type,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGraphResponse) Reset() {
	*x = WatchGraphResponse{}
	mi := &file_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGraphResponse) ProtoMessage() {}

func (x *WatchGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGraphResponse.ProtoReflect.Descriptor instead.
func (*WatchGraphResponse) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *WatchGraphResponse) GetType() GraphEventType {
	if x != nil {
		return x.Type
	}
	return GraphEventType_GRAPH_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchGraphResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// Graph contains one complete repository analysis.
type Graph struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Revision       string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	ModulePath     string                 `protobuf:"bytes,3,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	Scope          *AnalysisScope         `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Policy         *AnalysisPolicy        `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	Summary        *GraphSummary          `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Components     []*Component           `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
	Relationships  []*Relationship        `protobuf:"bytes,8,rep,name=relationships,proto3" json:"relationships,omitempty"`
	Functions      []*Function            `protobuf:"bytes,9,rep,name=functions,proto3" json:"functions,omitempty"`
	FunctionCalls  []*FunctionCall        `protobuf:"bytes,10,rep,name=function_calls,json=functionCalls,proto3" json:"function_calls,omitempty"`
	FunctionCycles []*Cycle               `protobuf:"bytes,11,rep,name=function_cycles,json=functionCycles,proto3" json:"function_cycles,omitempty"`
	Cycles         []*Cycle               `protobuf:"bytes,12,rep,name=cycles,proto3" json:"cycles,omitempty"`
	Diagnostics    []*Diagnostic          `protobuf:"bytes,13,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Findings       []*Finding             `protobuf:"bytes,14,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_v1_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{4}
}

func (x *Graph) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Graph) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *Graph) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *Graph) GetScope() *AnalysisScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Graph) GetPolicy() *AnalysisPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Graph) GetSummary() *GraphSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Graph) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Graph) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *Graph) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Graph) GetFunctionCalls() []*FunctionCall {
	if x != nil {
		return x.FunctionCalls
	}
	return nil
}

func (x *Graph) GetFunctionCycles() []*Cycle {
	if x != nil {
		return x.FunctionCycles
	}
	return nil
}

func (x *Graph) GetCycles() []*Cycle {
	if x != nil {
		return x.Cycles
	}
	return nil
}

func (x *Graph) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *Graph) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type AnalysisScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	IgnoredPaths  []string               `protobuf:"bytes,2,rep,name=ignored_paths,json=ignoredPaths,proto3" json:"ignored_paths,omitempty"`
	Components    *ComponentRules        `protobuf:"bytes,3,opt,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisScope) Reset() {
	*x = AnalysisScope{}
	mi := &file_v1_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisScope) ProtoMessage() {}

func (x *AnalysisScope) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisScope.ProtoReflect.Descriptor instead.
func (*AnalysisScope) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{5}
}

func (x *AnalysisScope) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *AnalysisScope) GetIgnoredPaths() []string {
	if x != nil {
		return x.IgnoredPaths
	}
	return nil
}

func (x *AnalysisScope) GetComponents() *ComponentRules {
	if x != nil {
		return x.Components
	}
	return nil
}

type ComponentRules struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Applications       []string                 `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	ApplicationModules []string                 `protobuf:"bytes,2,rep,name=application_modules,json=applicationModules,proto3" json:"application_modules,omitempty"`
	SharedModules      []string                 `protobuf:"bytes,3,rep,name=shared_modules,json=sharedModules,proto3" json:"shared_modules,omitempty"`
	Libraries          []string                 `protobuf:"bytes,4,rep,name=libraries,proto3" json:"libraries,omitempty"`
	Infrastructure     []string                 `protobuf:"bytes,5,rep,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	DevelopmentTools   []string                 `protobuf:"bytes,6,rep,name=development_tools,json=developmentTools,proto3" json:"development_tools,omitempty"`
	Taxonomy           []*ComponentCategoryRule `protobuf:"bytes,7,rep,name=taxonomy,proto3" json:"taxonomy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentRules) Reset() {
	*x = ComponentRules{}
	mi := &file_v1_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentRules) ProtoMessage() {}

func (x *ComponentRules) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentRules.ProtoReflect.Descriptor instead.
func (*ComponentRules) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentRules) GetApplications() []string {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ComponentRules) GetApplicationModules() []string {
	if x != nil {
		return x.ApplicationModules
	}
	return nil
}

func (x *ComponentRules) GetSharedModules() []string {
	if x != nil {
		return x.SharedModules
	}
	return nil
}

func (x *ComponentRules) GetLibraries() []string {
	if x != nil {
		return x.Libraries
	}
	return nil
}

func (x *ComponentRules) GetInfrastructure() []string {
	if x != nil {
		return x.Infrastructure
	}
	return nil
}

func (x *ComponentRules) GetDevelopmentTools() []string {
	if x != nil {
		return x.DevelopmentTools
	}
	return nil
}

func (x *ComponentRules) GetTaxonomy() []*ComponentCategoryRule {
	if x != nil {
		return x.Taxonomy
	}
	return nil
}

type ComponentCategoryRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentCategoryRule) Reset() {
	*x = ComponentCategoryRule{}
	mi := &file_v1_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentCategoryRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCategoryRule) ProtoMessage() {}

func (x *ComponentCategoryRule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCategoryRule.ProtoReflect.Descriptor instead.
func (*ComponentCategoryRule) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{7}
}

func (x *ComponentCategoryRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentCategoryRule) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ComponentCategoryRule) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type AnalysisPolicy struct {
	state                       protoimpl.MessageState           `protogen:"open.v1"`
	InstabilityFormula          string                           `protobuf:"bytes,1,opt,name=instability_formula,json=instabilityFormula,proto3" json:"instability_formula,omitempty"`
	FunctionInstabilityFormula  string                           `protobuf:"bytes,2,opt,name=function_instability_formula,json=functionInstabilityFormula,proto3" json:"function_instability_formula,omitempty"`
	FunctionCouplingDefinition  string                           `protobuf:"bytes,3,opt,name=function_coupling_definition,json=functionCouplingDefinition,proto3" json:"function_coupling_definition,omitempty"`
	FunctionCallResolution      string                           `protobuf:"bytes,4,opt,name=function_call_resolution,json=functionCallResolution,proto3" json:"function_call_resolution,omitempty"`
	IsolatedInstability         float64                          `protobuf:"fixed64,5,opt,name=isolated_instability,json=isolatedInstability,proto3" json:"isolated_instability,omitempty"`
	AbstractnessFormula         string                           `protobuf:"bytes,6,opt,name=abstractness_formula,json=abstractnessFormula,proto3" json:"abstractness_formula,omitempty"`
	UntypedAbstractness         float64                          `protobuf:"fixed64,7,opt,name=untyped_abstractness,json=untypedAbstractness,proto3" json:"untyped_abstractness,omitempty"`
	MainSequenceDistanceFormula string                           `protobuf:"bytes,8,opt,name=main_sequence_distance_formula,json=mainSequenceDistanceFormula,proto3" json:"main_sequence_distance_formula,omitempty"`
	StableLowAbstraction        *StableLowAbstractionPolicy      `protobuf:"bytes,9,opt,name=stable_low_abstraction,json=stableLowAbstraction,proto3" json:"stable_low_abstraction,omitempty"`
	StableDependencyPrinciple   *StableDependencyPrinciplePolicy `protobuf:"bytes,10,opt,name=stable_dependency_principle,json=stableDependencyPrinciple,proto3" json:"stable_dependency_principle,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AnalysisPolicy) Reset() {
	*x = AnalysisPolicy{}
	mi := &file_v1_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisPolicy) ProtoMessage() {}

func (x *AnalysisPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisPolicy.ProtoReflect.Descriptor instead.
func (*AnalysisPolicy) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisPolicy) GetInstabilityFormula() string {
	if x != nil {
		return x.InstabilityFormula
	}
	return ""
}

func (x *AnalysisPolicy) GetFunctionInstabilityFormula() string {
	if x != nil {
		return x.FunctionInstabilityFormula
	}
	return ""
}

func (x *AnalysisPolicy) GetFunctionCouplingDefinition() string {
	if x != nil {
		return x.FunctionCouplingDefinition
	}
	return ""
}

func (x *AnalysisPolicy) GetFunctionCallResolution() string {
	if x != nil {
		return x.FunctionCallResolution
	}
	return ""
}

func (x *AnalysisPolicy) GetIsolatedInstability() float64 {
	if x != nil {
		return x.IsolatedInstability
	}
	return 0
}

func (x *AnalysisPolicy) GetAbstractnessFormula() string {
	if x != nil {
		return x.AbstractnessFormula
	}
	return ""
}

func (x *AnalysisPolicy) GetUntypedAbstractness() float64 {
	if x != nil {
		return x.UntypedAbstractness
	}
	return 0
}

func (x *AnalysisPolicy) GetMainSequenceDistanceFormula() string {
	if x != nil {
		return x.MainSequenceDistanceFormula
	}
	return ""
}

func (x *AnalysisPolicy) GetStableLowAbstraction() *StableLowAbstractionPolicy {
	if x != nil {
		return x.StableLowAbstraction
	}
	return nil
}

func (x *AnalysisPolicy) GetStableDependencyPrinciple() *StableDependencyPrinciplePolicy {
	if x != nil {
		return x.StableDependencyPrinciple
	}
	return nil
}

type StableLowAbstractionPolicy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MinimumAfferentCoupling uint32                 `protobuf:"varint,1,opt,name=minimum_afferent_coupling,json=minimumAfferentCoupling,proto3" json:"minimum_afferent_coupling,omitempty"`
	MaximumInstability      float64                `protobuf:"fixed64,2,opt,name=maximum_instability,json=maximumInstability,proto3" json:"maximum_instability,omitempty"`
	MaximumAbstractness     float64                `protobuf:"fixed64,3,opt,name=maximum_abstractness,json=maximumAbstractness,proto3" json:"maximum_abstractness,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StableLowAbstractionPolicy) Reset() {
	*x = StableLowAbstractionPolicy{}
	mi := &file_v1_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StableLowAbstractionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableLowAbstractionPolicy) ProtoMessage() {}

func (x *StableLowAbstractionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StableLowAbstractionPolicy.ProtoReflect.Descriptor instead.
func (*StableLowAbstractionPolicy) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{9}
}

func (x *StableLowAbstractionPolicy) GetMinimumAfferentCoupling() uint32 {
	if x != nil {
		return x.MinimumAfferentCoupling
	}
	return 0
}

func (x *StableLowAbstractionPolicy) GetMaximumInstability() float64 {
	if x != nil {
		return x.MaximumInstability
	}
	return 0
}

func (x *StableLowAbstractionPolicy) GetMaximumAbstractness() float64 {
	if x != nil {
		return x.MaximumAbstractness
	}
	return 0
}

type StableDependencyPrinciplePolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequiredRelation string                 `protobuf:"bytes,1,opt,name=required_relation,json=requiredRelation,proto3" json:"required_relation,omitempty"`
	ProductionOnly   bool                   `protobuf:"varint,2,opt,name=production_only,json=productionOnly,proto3" json:"production_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StableDependencyPrinciplePolicy) Reset() {
	*x = StableDependencyPrinciplePolicy{}
	mi := &file_v1_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StableDependencyPrinciplePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableDependencyPrinciplePolicy) ProtoMessage() {}

func (x *StableDependencyPrinciplePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StableDependencyPrinciplePolicy.ProtoReflect.Descriptor instead.
func (*StableDependencyPrinciplePolicy) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{10}
}

func (x *StableDependencyPrinciplePolicy) GetRequiredRelation() string {
	if x != nil {
		return x.RequiredRelation
	}
	return ""
}

func (x *StableDependencyPrinciplePolicy) GetProductionOnly() bool {
	if x != nil {
		return x.ProductionOnly
	}
	return false
}

type GraphSummary struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	Components                          uint32                 `protobuf:"varint,1,opt,name=components,proto3" json:"components,omitempty"`
	Relationships                       uint32                 `protobuf:"varint,2,opt,name=relationships,proto3" json:"relationships,omitempty"`
	Functions                           uint32                 `protobuf:"varint,3,opt,name=functions,proto3" json:"functions,omitempty"`
	ProductionFunctions                 uint32                 `protobuf:"varint,4,opt,name=production_functions,json=productionFunctions,proto3" json:"production_functions,omitempty"`
	TestFunctions                       uint32                 `protobuf:"varint,5,opt,name=test_functions,json=testFunctions,proto3" json:"test_functions,omitempty"`
	FunctionCalls                       uint32                 `protobuf:"varint,6,opt,name=function_calls,json=functionCalls,proto3" json:"function_calls,omitempty"`
	FunctionCallSites                   uint32                 `protobuf:"varint,7,opt,name=function_call_sites,json=functionCallSites,proto3" json:"function_call_sites,omitempty"`
	CrossComponentFunctionCallSites     uint32                 `protobuf:"varint,8,opt,name=cross_component_function_call_sites,json=crossComponentFunctionCallSites,proto3" json:"cross_component_function_call_sites,omitempty"`
	FunctionCycles                      uint32                 `protobuf:"varint,9,opt,name=function_cycles,json=functionCycles,proto3" json:"function_cycles,omitempty"`
	ProductionRelationships             uint32                 `protobuf:"varint,10,opt,name=production_relationships,json=productionRelationships,proto3" json:"production_relationships,omitempty"`
	TestOnlyRelationships               uint32                 `protobuf:"varint,11,opt,name=test_only_relationships,json=testOnlyRelationships,proto3" json:"test_only_relationships,omitempty"`
	Applications                        uint32                 `protobuf:"varint,12,opt,name=applications,proto3" json:"applications,omitempty"`
	ApplicationModules                  uint32                 `protobuf:"varint,13,opt,name=application_modules,json=applicationModules,proto3" json:"application_modules,omitempty"`
	SharedModules                       uint32                 `protobuf:"varint,14,opt,name=shared_modules,json=sharedModules,proto3" json:"shared_modules,omitempty"`
	Libraries                           uint32                 `protobuf:"varint,15,opt,name=libraries,proto3" json:"libraries,omitempty"`
	Infrastructure                      uint32                 `protobuf:"varint,16,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	DevelopmentTools                    uint32                 `protobuf:"varint,17,opt,name=development_tools,json=developmentTools,proto3" json:"development_tools,omitempty"`
	Categories                          map[string]uint32      `protobuf:"bytes,18,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Cycles                              uint32                 `protobuf:"varint,19,opt,name=cycles,proto3" json:"cycles,omitempty"`
	RelationshipRuleViolations          uint32                 `protobuf:"varint,20,opt,name=relationship_rule_violations,json=relationshipRuleViolations,proto3" json:"relationship_rule_violations,omitempty"`
	StableDependencyPrincipleViolations uint32                 `protobuf:"varint,21,opt,name=stable_dependency_principle_violations,json=stableDependencyPrincipleViolations,proto3" json:"stable_dependency_principle_violations,omitempty"`
	StableLowAbstractionComponents      uint32                 `protobuf:"varint,22,opt,name=stable_low_abstraction_components,json=stableLowAbstractionComponents,proto3" json:"stable_low_abstraction_components,omitempty"`
	Findings                            uint32                 `protobuf:"varint,23,opt,name=findings,proto3" json:"findings,omitempty"`
	Errors                              uint32                 `protobuf:"varint,24,opt,name=errors,proto3" json:"errors,omitempty"`
	Warnings                            uint32                 `protobuf:"varint,25,opt,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *GraphSummary) Reset() {
	*x = GraphSummary{}
	mi := &file_v1_graph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSummary) ProtoMessage() {}

func (x *GraphSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSummary.ProtoReflect.Descriptor instead.
func (*GraphSummary) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{11}
}

func (x *GraphSummary) GetComponents() uint32 {
	if x != nil {
		return x.Components
	}
	return 0
}

func (x *GraphSummary) GetRelationships() uint32 {
	if x != nil {
		return x.Relationships
	}
	return 0
}

func (x *GraphSummary) GetFunctions() uint32 {
	if x != nil {
		return x.Functions
	}
	return 0
}

func (x *GraphSummary) GetProductionFunctions() uint32 {
	if x != nil {
		return x.ProductionFunctions
	}
	return 0
}

func (x *GraphSummary) GetTestFunctions() uint32 {
	if x != nil {
		return x.TestFunctions
	}
	return 0
}

func (x *GraphSummary) GetFunctionCalls() uint32 {
	if x != nil {
		return x.FunctionCalls
	}
	return 0
}

func (x *GraphSummary) GetFunctionCallSites() uint32 {
	if x != nil {
		return x.FunctionCallSites
	}
	return 0
}

func (x *GraphSummary) GetCrossComponentFunctionCallSites() uint32 {
	if x != nil {
		return x.CrossComponentFunctionCallSites
	}
	return 0
}

func (x *GraphSummary) GetFunctionCycles() uint32 {
	if x != nil {
		return x.FunctionCycles
	}
	return 0
}

func (x *GraphSummary) GetProductionRelationships() uint32 {
	if x != nil {
		return x.ProductionRelationships
	}
	return 0
}

func (x *GraphSummary) GetTestOnlyRelationships() uint32 {
	if x != nil {
		return x.TestOnlyRelationships
	}
	return 0
}

func (x *GraphSummary) GetApplications() uint32 {
	if x != nil {
		return x.Applications
	}
	return 0
}

func (x *GraphSummary) GetApplicationModules() uint32 {
	if x != nil {
		return x.ApplicationModules
	}
	return 0
}

func (x *GraphSummary) GetSharedModules() uint32 {
	if x != nil {
		return x.SharedModules
	}
	return 0
}

func (x *GraphSummary) GetLibraries() uint32 {
	if x != nil {
		return x.Libraries
	}
	return 0
}

func (x *GraphSummary) GetInfrastructure() uint32 {
	if x != nil {
		return x.Infrastructure
	}
	return 0
}

func (x *GraphSummary) GetDevelopmentTools() uint32 {
	if x != nil {
		return x.DevelopmentTools
	}
	return 0
}

func (x *GraphSummary) GetCategories() map[string]uint32 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GraphSummary) GetCycles() uint32 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *GraphSummary) GetRelationshipRuleViolations() uint32 {
	if x != nil {
		return x.RelationshipRuleViolations
	}
	return 0
}

func (x *GraphSummary) GetStableDependencyPrincipleViolations() uint32 {
	if x != nil {
		return x.StableDependencyPrincipleViolations
	}
	return 0
}

func (x *GraphSummary) GetStableLowAbstractionComponents() uint32 {
	if x != nil {
		return x.StableLowAbstractionComponents
	}
	return 0
}

func (x *GraphSummary) GetFindings() uint32 {
	if x != nil {
		return x.Findings
	}
	return 0
}

func (x *GraphSummary) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *GraphSummary) GetWarnings() uint32 {
	if x != nil {
		return x.Warnings
	}
	return 0
}

type Component struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Id                            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Category                      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Application                   string                 `protobuf:"bytes,5,opt,name=application,proto3" json:"application,omitempty"`
	Packages                      uint32                 `protobuf:"varint,6,opt,name=packages,proto3" json:"packages,omitempty"`
	SourceFiles                   uint32                 `protobuf:"varint,7,opt,name=source_files,json=sourceFiles,proto3" json:"source_files,omitempty"`
	ProductionFiles               uint32                 `protobuf:"varint,8,opt,name=production_files,json=productionFiles,proto3" json:"production_files,omitempty"`
	TestFiles                     uint32                 `protobuf:"varint,9,opt,name=test_files,json=testFiles,proto3" json:"test_files,omitempty"`
	DirectDependencies            uint32                 `protobuf:"varint,10,opt,name=direct_dependencies,json=directDependencies,proto3" json:"direct_dependencies,omitempty"`
	ProductionDependencies        uint32                 `protobuf:"varint,11,opt,name=production_dependencies,json=productionDependencies,proto3" json:"production_dependencies,omitempty"`
	TestOnlyDependencies          uint32                 `protobuf:"varint,12,opt,name=test_only_dependencies,json=testOnlyDependencies,proto3" json:"test_only_dependencies,omitempty"`
	DirectImportingComponents     uint32                 `protobuf:"varint,13,opt,name=direct_importing_components,json=directImportingComponents,proto3" json:"direct_importing_components,omitempty"`
	ProductionImportingComponents uint32                 `protobuf:"varint,14,opt,name=production_importing_components,json=productionImportingComponents,proto3" json:"production_importing_components,omitempty"`
	TestOnlyImportingComponents   uint32                 `protobuf:"varint,15,opt,name=test_only_importing_components,json=testOnlyImportingComponents,proto3" json:"test_only_importing_components,omitempty"`
	TransitiveDependencies        uint32                 `protobuf:"varint,16,opt,name=transitive_dependencies,json=transitiveDependencies,proto3" json:"transitive_dependencies,omitempty"`
	TransitiveImportingComponents uint32                 `protobuf:"varint,17,opt,name=transitive_importing_components,json=transitiveImportingComponents,proto3" json:"transitive_importing_components,omitempty"`
	ImporterPackages              uint32                 `protobuf:"varint,18,opt,name=importer_packages,json=importerPackages,proto3" json:"importer_packages,omitempty"`
	ProductionImporterPackages    uint32                 `protobuf:"varint,19,opt,name=production_importer_packages,json=productionImporterPackages,proto3" json:"production_importer_packages,omitempty"`
	TestImporterPackages          uint32                 `protobuf:"varint,20,opt,name=test_importer_packages,json=testImporterPackages,proto3" json:"test_importer_packages,omitempty"`
	UsingApplicationCount         uint32                 `protobuf:"varint,21,opt,name=using_application_count,json=usingApplicationCount,proto3" json:"using_application_count,omitempty"`
	UsingApplications             []string               `protobuf:"bytes,22,rep,name=using_applications,json=usingApplications,proto3" json:"using_applications,omitempty"`
	AfferentCoupling              uint32                 `protobuf:"varint,23,opt,name=afferent_coupling,json=afferentCoupling,proto3" json:"afferent_coupling,omitempty"`
	EfferentCoupling              uint32                 `protobuf:"varint,24,opt,name=efferent_coupling,json=efferentCoupling,proto3" json:"efferent_coupling,omitempty"`
	Instability                   float64                `protobuf:"fixed64,25,opt,name=instability,proto3" json:"instability,omitempty"`
	AbstractTypes                 uint32                 `protobuf:"varint,26,opt,name=abstract_types,json=abstractTypes,proto3" json:"abstract_types,omitempty"`
	ConcreteTypes                 uint32                 `protobuf:"varint,27,opt,name=concrete_types,json=concreteTypes,proto3" json:"concrete_types,omitempty"`
	Abstractness                  float64                `protobuf:"fixed64,28,opt,name=abstractness,proto3" json:"abstractness,omitempty"`
	MainSequenceDistance          float64                `protobuf:"fixed64,29,opt,name=main_sequence_distance,json=mainSequenceDistance,proto3" json:"main_sequence_distance,omitempty"`
	IsStableWithLowAbstraction    bool                   `protobuf:"varint,30,opt,name=is_stable_with_low_abstraction,json=isStableWithLowAbstraction,proto3" json:"is_stable_with_low_abstraction,omitempty"`
	InCycle                       bool                   `protobuf:"varint,31,opt,name=in_cycle,json=inCycle,proto3" json:"in_cycle,omitempty"`
	ProductionFunctions           uint32                 `protobuf:"varint,32,opt,name=production_functions,json=productionFunctions,proto3" json:"production_functions,omitempty"`
	TestFunctions                 uint32                 `protobuf:"varint,33,opt,name=test_functions,json=testFunctions,proto3" json:"test_functions,omitempty"`
	ProductionIncomingCallSites   uint32                 `protobuf:"varint,34,opt,name=production_incoming_call_sites,json=productionIncomingCallSites,proto3" json:"production_incoming_call_sites,omitempty"`
	ProductionOutgoingCallSites   uint32                 `protobuf:"varint,35,opt,name=production_outgoing_call_sites,json=productionOutgoingCallSites,proto3" json:"production_outgoing_call_sites,omitempty"`
	TestIncomingCallSites         uint32                 `protobuf:"varint,36,opt,name=test_incoming_call_sites,json=testIncomingCallSites,proto3" json:"test_incoming_call_sites,omitempty"`
	TestOutgoingCallSites         uint32                 `protobuf:"varint,37,opt,name=test_outgoing_call_sites,json=testOutgoingCallSites,proto3" json:"test_outgoing_call_sites,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_v1_graph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{12}
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Component) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Component) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *Component) GetPackages() uint32 {
	if x != nil {
		return x.Packages
	}
	return 0
}

func (x *Component) GetSourceFiles() uint32 {
	if x != nil {
		return x.SourceFiles
	}
	return 0
}

func (x *Component) GetProductionFiles() uint32 {
	if x != nil {
		return x.ProductionFiles
	}
	return 0
}

func (x *Component) GetTestFiles() uint32 {
	if x != nil {
		return x.TestFiles
	}
	return 0
}

func (x *Component) GetDirectDependencies() uint32 {
	if x != nil {
		return x.DirectDependencies
	}
	return 0
}

func (x *Component) GetProductionDependencies() uint32 {
	if x != nil {
		return x.ProductionDependencies
	}
	return 0
}

func (x *Component) GetTestOnlyDependencies() uint32 {
	if x != nil {
		return x.TestOnlyDependencies
	}
	return 0
}

func (x *Component) GetDirectImportingComponents() uint32 {
	if x != nil {
		return x.DirectImportingComponents
	}
	return 0
}

func (x *Component) GetProductionImportingComponents() uint32 {
	if x != nil {
		return x.ProductionImportingComponents
	}
	return 0
}

func (x *Component) GetTestOnlyImportingComponents() uint32 {
	if x != nil {
		return x.TestOnlyImportingComponents
	}
	return 0
}

func (x *Component) GetTransitiveDependencies() uint32 {
	if x != nil {
		return x.TransitiveDependencies
	}
	return 0
}

func (x *Component) GetTransitiveImportingComponents() uint32 {
	if x != nil {
		return x.TransitiveImportingComponents
	}
	return 0
}

func (x *Component) GetImporterPackages() uint32 {
	if x != nil {
		return x.ImporterPackages
	}
	return 0
}

func (x *Component) GetProductionImporterPackages() uint32 {
	if x != nil {
		return x.ProductionImporterPackages
	}
	return 0
}

func (x *Component) GetTestImporterPackages() uint32 {
	if x != nil {
		return x.TestImporterPackages
	}
	return 0
}

func (x *Component) GetUsingApplicationCount() uint32 {
	if x != nil {
		return x.UsingApplicationCount
	}
	return 0
}

func (x *Component) GetUsingApplications() []string {
	if x != nil {
		return x.UsingApplications
	}
	return nil
}

func (x *Component) GetAfferentCoupling() uint32 {
	if x != nil {
		return x.AfferentCoupling
	}
	return 0
}

func (x *Component) GetEfferentCoupling() uint32 {
	if x != nil {
		return x.EfferentCoupling
	}
	return 0
}

func (x *Component) GetInstability() float64 {
	if x != nil {
		return x.Instability
	}
	return 0
}

func (x *Component) GetAbstractTypes() uint32 {
	if x != nil {
		return x.AbstractTypes
	}
	return 0
}

func (x *Component) GetConcreteTypes() uint32 {
	if x != nil {
		return x.ConcreteTypes
	}
	return 0
}

func (x *Component) GetAbstractness() float64 {
	if x != nil {
		return x.Abstractness
	}
	return 0
}

func (x *Component) GetMainSequenceDistance() float64 {
	if x != nil {
		return x.MainSequenceDistance
	}
	return 0
}

func (x *Component) GetIsStableWithLowAbstraction() bool {
	if x != nil {
		return x.IsStableWithLowAbstraction
	}
	return false
}

func (x *Component) GetInCycle() bool {
	if x != nil {
		return x.InCycle
	}
	return false
}

func (x *Component) GetProductionFunctions() uint32 {
	if x != nil {
		return x.ProductionFunctions
	}
	return 0
}

func (x *Component) GetTestFunctions() uint32 {
	if x != nil {
		return x.TestFunctions
	}
	return 0
}

func (x *Component) GetProductionIncomingCallSites() uint32 {
	if x != nil {
		return x.ProductionIncomingCallSites
	}
	return 0
}

func (x *Component) GetProductionOutgoingCallSites() uint32 {
	if x != nil {
		return x.ProductionOutgoingCallSites
	}
	return 0
}

func (x *Component) GetTestIncomingCallSites() uint32 {
	if x != nil {
		return x.TestIncomingCallSites
	}
	return 0
}

func (x *Component) GetTestOutgoingCallSites() uint32 {
	if x != nil {
		return x.TestOutgoingCallSites
	}
	return 0
}

type Relationship struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	Source                            string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target                            string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ProductionReferencingFiles        uint32                 `protobuf:"varint,3,opt,name=production_referencing_files,json=productionReferencingFiles,proto3" json:"production_referencing_files,omitempty"`
	TestReferencingFiles              uint32                 `protobuf:"varint,4,opt,name=test_referencing_files,json=testReferencingFiles,proto3" json:"test_referencing_files,omitempty"`
	SourcePackages                    []string               `protobuf:"bytes,5,rep,name=source_packages,json=sourcePackages,proto3" json:"source_packages,omitempty"`
	TargetPackages                    []string               `protobuf:"bytes,6,rep,name=target_packages,json=targetPackages,proto3" json:"target_packages,omitempty"`
	ImportSites                       []*ImportSite          `protobuf:"bytes,7,rep,name=import_sites,json=importSites,proto3" json:"import_sites,omitempty"`
	ProductionFunctionCallSites       uint32                 `protobuf:"varint,8,opt,name=production_function_call_sites,json=productionFunctionCallSites,proto3" json:"production_function_call_sites,omitempty"`
	TestFunctionCallSites             uint32                 `protobuf:"varint,9,opt,name=test_function_call_sites,json=testFunctionCallSites,proto3" json:"test_function_call_sites,omitempty"`
	CallerFunctions                   uint32                 `protobuf:"varint,10,opt,name=caller_functions,json=callerFunctions,proto3" json:"caller_functions,omitempty"`
	CalleeFunctions                   uint32                 `protobuf:"varint,11,opt,name=callee_functions,json=calleeFunctions,proto3" json:"callee_functions,omitempty"`
	TestOnly                          bool                   `protobuf:"varint,12,opt,name=test_only,json=testOnly,proto3" json:"test_only,omitempty"`
	ViolatesStableDependencyPrinciple bool                   `protobuf:"varint,13,opt,name=violates_stable_dependency_principle,json=violatesStableDependencyPrinciple,proto3" json:"violates_stable_dependency_principle,omitempty"`
	RuleViolations                    []string               `protobuf:"bytes,14,rep,name=rule_violations,json=ruleViolations,proto3" json:"rule_violations,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_v1_graph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{13}
}

func (x *Relationship) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Relationship) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Relationship) GetProductionReferencingFiles() uint32 {
	if x != nil {
		return x.ProductionReferencingFiles
	}
	return 0
}

func (x *Relationship) GetTestReferencingFiles() uint32 {
	if x != nil {
		return x.TestReferencingFiles
	}
	return 0
}

func (x *Relationship) GetSourcePackages() []string {
	if x != nil {
		return x.SourcePackages
	}
	return nil
}

func (x *Relationship) GetTargetPackages() []string {
	if x != nil {
		return x.TargetPackages
	}
	return nil
}

func (x *Relationship) GetImportSites() []*ImportSite {
	if x != nil {
		return x.ImportSites
	}
	return nil
}

func (x *Relationship) GetProductionFunctionCallSites() uint32 {
	if x != nil {
		return x.ProductionFunctionCallSites
	}
	return 0
}

func (x *Relationship) GetTestFunctionCallSites() uint32 {
	if x != nil {
		return x.TestFunctionCallSites
	}
	return 0
}

func (x *Relationship) GetCallerFunctions() uint32 {
	if x != nil {
		return x.CallerFunctions
	}
	return 0
}

func (x *Relationship) GetCalleeFunctions() uint32 {
	if x != nil {
		return x.CalleeFunctions
	}
	return 0
}

func (x *Relationship) GetTestOnly() bool {
	if x != nil {
		return x.TestOnly
	}
	return false
}

func (x *Relationship) GetViolatesStableDependencyPrinciple() bool {
	if x != nil {
		return x.ViolatesStableDependencyPrinciple
	}
	return false
}

func (x *Relationship) GetRuleViolations() []string {
	if x != nil {
		return x.RuleViolations
	}
	return nil
}

type ImportSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePackage string                 `protobuf:"bytes,1,opt,name=source_package,json=sourcePackage,proto3" json:"source_package,omitempty"`
	TargetPackage string                 `protobuf:"bytes,2,opt,name=target_package,json=targetPackage,proto3" json:"target_package,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Line          uint32                 `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Test          bool                   `protobuf:"varint,6,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSite) Reset() {
	*x = ImportSite{}
	mi := &file_v1_graph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSite) ProtoMessage() {}

func (x *ImportSite) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSite.ProtoReflect.Descriptor instead.
func (*ImportSite) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{14}
}

func (x *ImportSite) GetSourcePackage() string {
	if x != nil {
		return x.SourcePackage
	}
	return ""
}

func (x *ImportSite) GetTargetPackage() string {
	if x != nil {
		return x.TargetPackage
	}
	return ""
}

func (x *ImportSite) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImportSite) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ImportSite) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ImportSite) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

type Function struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Id                            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Package                       string                 `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	Component                     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	Path                          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Line                          uint32                 `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	Receiver                      string                 `protobuf:"bytes,7,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Method                        bool                   `protobuf:"varint,8,opt,name=method,proto3" json:"method,omitempty"`
	Exported                      bool                   `protobuf:"varint,9,opt,name=exported,proto3" json:"exported,omitempty"`
	Test                          bool                   `protobuf:"varint,10,opt,name=test,proto3" json:"test,omitempty"`
	Synthetic                     bool                   `protobuf:"varint,11,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	InAnalysisScope               bool                   `protobuf:"varint,12,opt,name=in_analysis_scope,json=inAnalysisScope,proto3" json:"in_analysis_scope,omitempty"`
	AfferentCoupling              uint32                 `protobuf:"varint,13,opt,name=afferent_coupling,json=afferentCoupling,proto3" json:"afferent_coupling,omitempty"`
	EfferentCoupling              uint32                 `protobuf:"varint,14,opt,name=efferent_coupling,json=efferentCoupling,proto3" json:"efferent_coupling,omitempty"`
	TestAfferentCoupling          uint32                 `protobuf:"varint,15,opt,name=test_afferent_coupling,json=testAfferentCoupling,proto3" json:"test_afferent_coupling,omitempty"`
	TestEfferentCoupling          uint32                 `protobuf:"varint,16,opt,name=test_efferent_coupling,json=testEfferentCoupling,proto3" json:"test_efferent_coupling,omitempty"`
	IncomingCallSites             uint32                 `protobuf:"varint,17,opt,name=incoming_call_sites,json=incomingCallSites,proto3" json:"incoming_call_sites,omitempty"`
	OutgoingCallSites             uint32                 `protobuf:"varint,18,opt,name=outgoing_call_sites,json=outgoingCallSites,proto3" json:"outgoing_call_sites,omitempty"`
	TestIncomingCallSites         uint32                 `protobuf:"varint,19,opt,name=test_incoming_call_sites,json=testIncomingCallSites,proto3" json:"test_incoming_call_sites,omitempty"`
	TestOutgoingCallSites         uint32                 `protobuf:"varint,20,opt,name=test_outgoing_call_sites,json=testOutgoingCallSites,proto3" json:"test_outgoing_call_sites,omitempty"`
	CrossComponentCallerFunctions uint32                 `protobuf:"varint,21,opt,name=cross_component_caller_functions,json=crossComponentCallerFunctions,proto3" json:"cross_component_caller_functions,omitempty"`
	CrossComponentCalleeFunctions uint32                 `protobuf:"varint,22,opt,name=cross_component_callee_functions,json=crossComponentCalleeFunctions,proto3" json:"cross_component_callee_functions,omitempty"`
	TransitiveCallerFunctions     uint32                 `protobuf:"varint,23,opt,name=transitive_caller_functions,json=transitiveCallerFunctions,proto3" json:"transitive_caller_functions,omitempty"`
	TransitiveCalleeFunctions     uint32                 `protobuf:"varint,24,opt,name=transitive_callee_functions,json=transitiveCalleeFunctions,proto3" json:"transitive_callee_functions,omitempty"`
	UsingApplicationCount         uint32                 `protobuf:"varint,25,opt,name=using_application_count,json=usingApplicationCount,proto3" json:"using_application_count,omitempty"`
	UsingApplications             []string               `protobuf:"bytes,26,rep,name=using_applications,json=usingApplications,proto3" json:"using_applications,omitempty"`
	InCycle                       bool                   `protobuf:"varint,27,opt,name=in_cycle,json=inCycle,proto3" json:"in_cycle,omitempty"`
	Instability                   float64                `protobuf:"fixed64,28,opt,name=instability,proto3" json:"instability,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_v1_graph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{15}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Function) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Function) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Function) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Function) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Function) GetMethod() bool {
	if x != nil {
		return x.Method
	}
	return false
}

func (x *Function) GetExported() bool {
	if x != nil {
		return x.Exported
	}
	return false
}

func (x *Function) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

func (x *Function) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

func (x *Function) GetInAnalysisScope() bool {
	if x != nil {
		return x.InAnalysisScope
	}
	return false
}

func (x *Function) GetAfferentCoupling() uint32 {
	if x != nil {
		return x.AfferentCoupling
	}
	return 0
}

func (x *Function) GetEfferentCoupling() uint32 {
	if x != nil {
		return x.EfferentCoupling
	}
	return 0
}

func (x *Function) GetTestAfferentCoupling() uint32 {
	if x != nil {
		return x.TestAfferentCoupling
	}
	return 0
}

func (x *Function) GetTestEfferentCoupling() uint32 {
	if x != nil {
		return x.TestEfferentCoupling
	}
	return 0
}

func (x *Function) GetIncomingCallSites() uint32 {
	if x != nil {
		return x.IncomingCallSites
	}
	return 0
}

func (x *Function) GetOutgoingCallSites() uint32 {
	if x != nil {
		return x.OutgoingCallSites
	}
	return 0
}

func (x *Function) GetTestIncomingCallSites() uint32 {
	if x != nil {
		return x.TestIncomingCallSites
	}
	return 0
}

func (x *Function) GetTestOutgoingCallSites() uint32 {
	if x != nil {
		return x.TestOutgoingCallSites
	}
	return 0
}

func (x *Function) GetCrossComponentCallerFunctions() uint32 {
	if x != nil {
		return x.CrossComponentCallerFunctions
	}
	return 0
}

func (x *Function) GetCrossComponentCalleeFunctions() uint32 {
	if x != nil {
		return x.CrossComponentCalleeFunctions
	}
	return 0
}

func (x *Function) GetTransitiveCallerFunctions() uint32 {
	if x != nil {
		return x.TransitiveCallerFunctions
	}
	return 0
}

func (x *Function) GetTransitiveCalleeFunctions() uint32 {
	if x != nil {
		return x.TransitiveCalleeFunctions
	}
	return 0
}

func (x *Function) GetUsingApplicationCount() uint32 {
	if x != nil {
		return x.UsingApplicationCount
	}
	return 0
}

func (x *Function) GetUsingApplications() []string {
	if x != nil {
		return x.UsingApplications
	}
	return nil
}

func (x *Function) GetInCycle() bool {
	if x != nil {
		return x.InCycle
	}
	return false
}

func (x *Function) GetInstability() float64 {
	if x != nil {
		return x.Instability
	}
	return 0
}

type FunctionCall struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	SourceComponent string                 `protobuf:"bytes,3,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`
	TargetComponent string                 `protobuf:"bytes,4,opt,name=target_component,json=targetComponent,proto3" json:"target_component,omitempty"`
	CallSites       []*CallSite            `protobuf:"bytes,5,rep,name=call_sites,json=callSites,proto3" json:"call_sites,omitempty"`
	Calls           uint32                 `protobuf:"varint,6,opt,name=calls,proto3" json:"calls,omitempty"`
	TestOnly        bool                   `protobuf:"varint,7,opt,name=test_only,json=testOnly,proto3" json:"test_only,omitempty"`
	CrossComponent  bool                   `protobuf:"varint,8,opt,name=cross_component,json=crossComponent,proto3" json:"cross_component,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_v1_graph_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{16}
}

func (x *FunctionCall) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FunctionCall) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FunctionCall) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *FunctionCall) GetTargetComponent() string {
	if x != nil {
		return x.TargetComponent
	}
	return ""
}

func (x *FunctionCall) GetCallSites() []*CallSite {
	if x != nil {
		return x.CallSites
	}
	return nil
}

func (x *FunctionCall) GetCalls() uint32 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *FunctionCall) GetTestOnly() bool {
	if x != nil {
		return x.TestOnly
	}
	return false
}

func (x *FunctionCall) GetCrossComponent() bool {
	if x != nil {
		return x.CrossComponent
	}
	return false
}

type CallSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Line          uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSite) Reset() {
	*x = CallSite{}
	mi := &file_v1_graph_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSite) ProtoMessage() {}

func (x *CallSite) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSite.ProtoReflect.Descriptor instead.
func (*CallSite) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{17}
}

func (x *CallSite) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallSite) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CallSite) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type Cycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cycle) Reset() {
	*x = Cycle{}
	mi := &file_v1_graph_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cycle) ProtoMessage() {}

func (x *Cycle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cycle.ProtoReflect.Descriptor instead.
func (*Cycle) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{18}
}

func (x *Cycle) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_v1_graph_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{19}
}

func (x *Diagnostic) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Components    []string               `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_v1_graph_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_v1_graph_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_v1_graph_proto_rawDescGZIP(), []int{20}
}

func (x *Finding) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Finding) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Finding) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Finding) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_v1_graph_proto protoreflect.FileDescriptor

const file_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/graph.proto\x12\fgoconduct.v1\x1a\x1bbuf/validate/validate.proto\"\x92\x01\n" +
	"\x0fGetGraphRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\bR\arefresh\x125\n" +
	"\tcache_key\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^$|^[a-f0-9]{64}$R\bcacheKey\x12.\n" +
	"\x0ecache_protocol\x18\x03 \x01(\rB\a\xbaH\x04*\x02\x18\x01R\rcacheProtocol\"\x81\x01\n" +
	"\x10GetGraphResponse\x12)\n" +
	"\x05graph\x18\x01 \x01(\v2\x13.goconduct.v1.GraphR\x05graph\x12\x1b\n" +
	"\tcache_key\x18\x02 \x01(\tR\bcacheKey\x12%\n" +
	"\x0ecache_protocol\x18\x03 \x01(\rR\rcacheProtocol\"R\n" +
	"\x11WatchGraphRequest\x12=\n" +
	"\rfrom_revision\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x11^$|^[a-f0-9]{64}$R\ffromRevision\"b\n" +
	"\x12WatchGraphResponse\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.goconduct.v1.GraphEventTypeR\x04type\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\"\xd8\x05\n" +
	"\x05Graph\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1f\n" +
	"\vmodule_path\x18\x03 \x01(\tR\n" +
	"modulePath\x121\n" +
	"\x05scope\x18\x04 \x01(\v2\x1b.goconduct.v1.AnalysisScopeR\x05scope\x124\n" +
	"\x06policy\x18\x05 \x01(\v2\x1c.goconduct.v1.AnalysisPolicyR\x06policy\x124\n" +
	"\asummary\x18\x06 \x01(\v2\x1a.goconduct.v1.GraphSummaryR\asummary\x127\n" +
	"\n" +
	"components\x18\a \x03(\v2\x17.goconduct.v1.ComponentR\n" +
	"components\x12@\n" +
	"\rrelationships\x18\b \x03(\v2\x1a.goconduct.v1.RelationshipR\rrelationships\x124\n" +
	"\tfunctions\x18\t \x03(\v2\x16.goconduct.v1.FunctionR\tfunctions\x12A\n" +
	"\x0efunction_calls\x18\n" +
	" \x03(\v2\x1a.goconduct.v1.FunctionCallR\rfunctionCalls\x12<\n" +
	"\x0ffunction_cycles\x18\v \x03(\v2\x13.goconduct.v1.CycleR\x0efunctionCycles\x12+\n" +
	"\x06cycles\x18\f \x03(\v2\x13.goconduct.v1.CycleR\x06cycles\x12:\n" +
	"\vdiagnostics\x18\r \x03(\v2\x18.goconduct.v1.DiagnosticR\vdiagnostics\x121\n" +
	"\bfindings\x18\x0e \x03(\v2\x15.goconduct.v1.FindingR\bfindings\"\x88\x01\n" +
	"\rAnalysisScope\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12#\n" +
	"\rignored_paths\x18\x02 \x03(\tR\fignoredPaths\x12<\n" +
	"\n" +
	"components\x18\x03 \x01(\v2\x1c.goconduct.v1.ComponentRulesR\n" +
	"components\"\xc0\x02\n" +
	"\x0eComponentRules\x12\"\n" +
	"\fapplications\x18\x01 \x03(\tR\fapplications\x12/\n" +
	"\x13application_modules\x18\x02 \x03(\tR\x12applicationModules\x12%\n" +
	"\x0eshared_modules\x18\x03 \x03(\tR\rsharedModules\x12\x1c\n" +
	"\tlibraries\x18\x04 \x03(\tR\tlibraries\x12&\n" +
	"\x0einfrastructure\x18\x05 \x03(\tR\x0einfrastructure\x12+\n" +
	"\x11development_tools\x18\x06 \x03(\tR\x10developmentTools\x12?\n" +
	"\btaxonomy\x18\a \x03(\v2#.goconduct.v1.ComponentCategoryRuleR\btaxonomy\"Q\n" +
	"\x15ComponentCategoryRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\"\xac\x05\n" +
	"\x0eAnalysisPolicy\x12/\n" +
	"\x13instability_formula\x18\x01 \x01(\tR\x12instabilityFormula\x12@\n" +
	"\x1cfunction_instability_formula\x18\x02 \x01(\tR\x1afunctionInstabilityFormula\x12@\n" +
	"\x1cfunction_coupling_definition\x18\x03 \x01(\tR\x1afunctionCouplingDefinition\x128\n" +
	"\x18function_call_resolution\x18\x04 \x01(\tR\x16functionCallResolution\x121\n" +
	"\x14isolated_instability\x18\x05 \x01(\x01R\x13isolatedInstability\x121\n" +
	"\x14abstractness_formula\x18\x06 \x01(\tR\x13abstractnessFormula\x121\n" +
	"\x14untyped_abstractness\x18\a \x01(\x01R\x13untypedAbstractness\x12C\n" +
	"\x1emain_sequence_distance_formula\x18\b \x01(\tR\x1bmainSequenceDistanceFormula\x12^\n" +
	"\x16stable_low_abstraction\x18\t \x01(\v2(.goconduct.v1.StableLowAbstractionPolicyR\x14stableLowAbstraction\x12m\n" +
	"\x1bstable_dependency_principle\x18\n" +
	" \x01(\v2-.goconduct.v1.StableDependencyPrinciplePolicyR\x19stableDependencyPrinciple\"\xbc\x01\n" +
	"\x1aStableLowAbstractionPolicy\x12:\n" +
	"\x19minimum_afferent_coupling\x18\x01 \x01(\rR\x17minimumAfferentCoupling\x12/\n" +
	"\x13maximum_instability\x18\x02 \x01(\x01R\x12maximumInstability\x121\n" +
	"\x14maximum_abstractness\x18\x03 \x01(\x01R\x13maximumAbstractness\"w\n" +
	"\x1fStableDependencyPrinciplePolicy\x12+\n" +
	"\x11required_relation\x18\x01 \x01(\tR\x10requiredRelation\x12'\n" +
	"\x0fproduction_only\x18\x02 \x01(\bR\x0eproductionOnly\"\xd1\t\n" +
	"\fGraphSummary\x12\x1e\n" +
	"\n" +
	"components\x18\x01 \x01(\rR\n" +
	"components\x12$\n" +
	"\rrelationships\x18\x02 \x01(\rR\rrelationships\x12\x1c\n" +
	"\tfunctions\x18\x03 \x01(\rR\tfunctions\x121\n" +
	"\x14production_functions\x18\x04 \x01(\rR\x13productionFunctions\x12%\n" +
	"\x0etest_functions\x18\x05 \x01(\rR\rtestFunctions\x12%\n" +
	"\x0efunction_calls\x18\x06 \x01(\rR\rfunctionCalls\x12.\n" +
	"\x13function_call_sites\x18\a \x01(\rR\x11functionCallSites\x12L\n" +
	"#cross_component_function_call_sites\x18\b \x01(\rR\x1fcrossComponentFunctionCallSites\x12'\n" +
	"\x0ffunction_cycles\x18\t \x01(\rR\x0efunctionCycles\x129\n" +
	"\x18production_relationships\x18\n" +
	" \x01(\rR\x17productionRelationships\x126\n" +
	"\x17test_only_relationships\x18\v \x01(\rR\x15testOnlyRelationships\x12\"\n" +
	"\fapplications\x18\f \x01(\rR\fapplications\x12/\n" +
	"\x13application_modules\x18\r \x01(\rR\x12applicationModules\x12%\n" +
	"\x0eshared_modules\x18\x0e \x01(\rR\rsharedModules\x12\x1c\n" +
	"\tlibraries\x18\x0f \x01(\rR\tlibraries\x12&\n" +
	"\x0einfrastructure\x18\x10 \x01(\rR\x0einfrastructure\x12+\n" +
	"\x11development_tools\x18\x11 \x01(\rR\x10developmentTools\x12J\n" +
	"\n" +
	"categories\x18\x12 \x03(\v2*.goconduct.v1.GraphSummary.CategoriesEntryR\n" +
	"categories\x12\x16\n" +
	"\x06cycles\x18\x13 \x01(\rR\x06cycles\x12@\n" +
	"\x1crelationship_rule_violations\x18\x14 \x01(\rR\x1arelationshipRuleViolations\x12S\n" +
	"&stable_dependency_principle_violations\x18\x15 \x01(\rR#stableDependencyPrincipleViolations\x12I\n" +
	"!stable_low_abstraction_components\x18\x16 \x01(\rR\x1estableLowAbstractionComponents\x12\x1a\n" +
	"\bfindings\x18\x17 \x01(\rR\bfindings\x12\x16\n" +
	"\x06errors\x18\x18 \x01(\rR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x19 \x01(\rR\bwarnings\x1a=\n" +
	"\x0fCategoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xdd\r\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vapplication\x18\x05 \x01(\tR\vapplication\x12\x1a\n" +
	"\bpackages\x18\x06 \x01(\rR\bpackages\x12!\n" +
	"\fsource_files\x18\a \x01(\rR\vsourceFiles\x12)\n" +
	"\x10production_files\x18\b \x01(\rR\x0fproductionFiles\x12\x1d\n" +
	"\n" +
	"test_files\x18\t \x01(\rR\ttestFiles\x12/\n" +
	"\x13direct_dependencies\x18\n" +
	" \x01(\rR\x12directDependencies\x127\n" +
	"\x17production_dependencies\x18\v \x01(\rR\x16productionDependencies\x124\n" +
	"\x16test_only_dependencies\x18\f \x01(\rR\x14testOnlyDependencies\x12>\n" +
	"\x1bdirect_importing_components\x18\r \x01(\rR\x19directImportingComponents\x12F\n" +
	"\x1fproduction_importing_components\x18\x0e \x01(\rR\x1dproductionImportingComponents\x12C\n" +
	"\x1etest_only_importing_components\x18\x0f \x01(\rR\x1btestOnlyImportingComponents\x127\n" +
	"\x17transitive_dependencies\x18\x10 \x01(\rR\x16transitiveDependencies\x12F\n" +
	"\x1ftransitive_importing_components\x18\x11 \x01(\rR\x1dtransitiveImportingComponents\x12+\n" +
	"\x11importer_packages\x18\x12 \x01(\rR\x10importerPackages\x12@\n" +
	"\x1cproduction_importer_packages\x18\x13 \x01(\rR\x1aproductionImporterPackages\x124\n" +
	"\x16test_importer_packages\x18\x14 \x01(\rR\x14testImporterPackages\x126\n" +
	"\x17using_application_count\x18\x15 \x01(\rR\x15usingApplicationCount\x12-\n" +
	"\x12using_applications\x18\x16 \x03(\tR\x11usingApplications\x12+\n" +
	"\x11afferent_coupling\x18\x17 \x01(\rR\x10afferentCoupling\x12+\n" +
	"\x11efferent_coupling\x18\x18 \x01(\rR\x10efferentCoupling\x12 \n" +
	"\vinstability\x18\x19 \x01(\x01R\vinstability\x12%\n" +
	"\x0eabstract_types\x18\x1a \x01(\rR\rabstractTypes\x12%\n" +
	"\x0econcrete_types\x18\x1b \x01(\rR\rconcreteTypes\x12\"\n" +
	"\fabstractness\x18\x1c \x01(\x01R\fabstractness\x124\n" +
	"\x16main_sequence_distance\x18\x1d \x01(\x01R\x14mainSequenceDistance\x12B\n" +
	"\x1eis_stable_with_low_abstraction\x18\x1e \x01(\bR\x1aisStableWithLowAbstraction\x12\x19\n" +
	"\bin_cycle\x18\x1f \x01(\bR\ainCycle\x121\n" +
	"\x14production_functions\x18  \x01(\rR\x13productionFunctions\x12%\n" +
	"\x0etest_functions\x18! \x01(\rR\rtestFunctions\x12C\n" +
	"\x1eproduction_incoming_call_sites\x18\" \x01(\rR\x1bproductionIncomingCallSites\x12C\n" +
	"\x1eproduction_outgoing_call_sites\x18# \x01(\rR\x1bproductionOutgoingCallSites\x127\n" +
	"\x18test_incoming_call_sites\x18$ \x01(\rR\x15testIncomingCallSites\x127\n" +
	"\x18test_outgoing_call_sites\x18% \x01(\rR\x15testOutgoingCallSites\"\xb0\x05\n" +
	"\fRelationship\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12@\n" +
	"\x1cproduction_referencing_files\x18\x03 \x01(\rR\x1aproductionReferencingFiles\x124\n" +
	"\x16test_referencing_files\x18\x04 \x01(\rR\x14testReferencingFiles\x12'\n" +
	"\x0fsource_packages\x18\x05 \x03(\tR\x0esourcePackages\x12'\n" +
	"\x0ftarget_packages\x18\x06 \x03(\tR\x0etargetPackages\x12;\n" +
	"\fimport_sites\x18\a \x03(\v2\x18.goconduct.v1.ImportSiteR\vimportSites\x12C\n" +
	"\x1eproduction_function_call_sites\x18\b \x01(\rR\x1bproductionFunctionCallSites\x127\n" +
	"\x18test_function_call_sites\x18\t \x01(\rR\x15testFunctionCallSites\x12)\n" +
	"\x10caller_functions\x18\n" +
	" \x01(\rR\x0fcallerFunctions\x12)\n" +
	"\x10callee_functions\x18\v \x01(\rR\x0fcalleeFunctions\x12\x1b\n" +
	"\ttest_only\x18\f \x01(\bR\btestOnly\x12O\n" +
	"$violates_stable_dependency_principle\x18\r \x01(\bR!violatesStableDependencyPrinciple\x12'\n" +
	"\x0frule_violations\x18\x0e \x03(\tR\x0eruleViolations\"\xac\x01\n" +
	"\n" +
	"ImportSite\x12%\n" +
	"\x0esource_package\x18\x01 \x01(\tR\rsourcePackage\x12%\n" +
	"\x0etarget_package\x18\x02 \x01(\tR\rtargetPackage\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x04 \x01(\rR\x04line\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x12\n" +
	"\x04test\x18\x06 \x01(\bR\x04test\"\x8a\t\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x06 \x01(\rR\x04line\x12\x1a\n" +
	"\breceiver\x18\a \x01(\tR\breceiver\x12\x16\n" +
	"\x06method\x18\b \x01(\bR\x06method\x12\x1a\n" +
	"\bexported\x18\t \x01(\bR\bexported\x12\x12\n" +
	"\x04test\x18\n" +
	" \x01(\bR\x04test\x12\x1c\n" +
	"\tsynthetic\x18\v \x01(\bR\tsynthetic\x12*\n" +
	"\x11in_analysis_scope\x18\f \x01(\bR\x0finAnalysisScope\x12+\n" +
	"\x11afferent_coupling\x18\r \x01(\rR\x10afferentCoupling\x12+\n" +
	"\x11efferent_coupling\x18\x0e \x01(\rR\x10efferentCoupling\x124\n" +
	"\x16test_afferent_coupling\x18\x0f \x01(\rR\x14testAfferentCoupling\x124\n" +
	"\x16test_efferent_coupling\x18\x10 \x01(\rR\x14testEfferentCoupling\x12.\n" +
	"\x13incoming_call_sites\x18\x11 \x01(\rR\x11incomingCallSites\x12.\n" +
	"\x13outgoing_call_sites\x18\x12 \x01(\rR\x11outgoingCallSites\x127\n" +
	"\x18test_incoming_call_sites\x18\x13 \x01(\rR\x15testIncomingCallSites\x127\n" +
	"\x18test_outgoing_call_sites\x18\x14 \x01(\rR\x15testOutgoingCallSites\x12G\n" +
	" cross_component_caller_functions\x18\x15 \x01(\rR\x1dcrossComponentCallerFunctions\x12G\n" +
	" cross_component_callee_functions\x18\x16 \x01(\rR\x1dcrossComponentCalleeFunctions\x12>\n" +
	"\x1btransitive_caller_functions\x18\x17 \x01(\rR\x19transitiveCallerFunctions\x12>\n" +
	"\x1btransitive_callee_functions\x18\x18 \x01(\rR\x19transitiveCalleeFunctions\x126\n" +
	"\x17using_application_count\x18\x19 \x01(\rR\x15usingApplicationCount\x12-\n" +
	"\x12using_applications\x18\x1a \x03(\tR\x11usingApplications\x12\x19\n" +
	"\bin_cycle\x18\x1b \x01(\bR\ainCycle\x12 \n" +
	"\vinstability\x18\x1c \x01(\x01R\vinstability\"\xa7\x02\n" +
	"\fFunctionCall\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12)\n" +
	"\x10source_component\x18\x03 \x01(\tR\x0fsourceComponent\x12)\n" +
	"\x10target_component\x18\x04 \x01(\tR\x0ftargetComponent\x125\n" +
	"\n" +
	"call_sites\x18\x05 \x03(\v2\x16.goconduct.v1.CallSiteR\tcallSites\x12\x14\n" +
	"\x05calls\x18\x06 \x01(\rR\x05calls\x12\x1b\n" +
	"\ttest_only\x18\a \x01(\bR\btestOnly\x12'\n" +
	"\x0fcross_component\x18\b \x01(\bR\x0ecrossComponent\"J\n" +
	"\bCallSite\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\"!\n" +
	"\x05Cycle\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\":\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x02\n" +
	"\aFinding\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"components\x18\a \x03(\tR\n" +
	"components\x12<\n" +
	"\ametrics\x18\b \x03(\v2\".goconduct.v1.Finding.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01*\x8c\x01\n" +
	"\x0eGraphEventType\x12 \n" +
	"\x1cGRAPH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16GRAPH_EVENT_TYPE_READY\x10\x01\x12\x1c\n" +
	"\x18GRAPH_EVENT_TYPE_CHANGED\x10\x02\x12\x1e\n" +
	"\x1aGRAPH_EVENT_TYPE_HEARTBEAT\x10\x032\xac\x01\n" +
	"\fGraphService\x12I\n" +
	"\bGetGraph\x12\x1d.goconduct.v1.GetGraphRequest\x1a\x1e.goconduct.v1.GetGraphResponse\x12Q\n" +
	"\n" +
	"WatchGraph\x12\x1f.goconduct.v1.WatchGraphRequest\x1a .goconduct.v1.WatchGraphResponse0\x01B?Z=github.com/cgardev/goconduct/internal/protogen/v1;goconductv1b\x06proto3"

var (
	file_v1_graph_proto_rawDescOnce sync.Once
	file_v1_graph_proto_rawDescData []byte
)

func file_v1_graph_proto_rawDescGZIP() []byte {
	file_v1_graph_proto_rawDescOnce.Do(func() {
		file_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_graph_proto_rawDesc), len(file_v1_graph_proto_rawDesc)))
	})
	return file_v1_graph_proto_rawDescData
}

var file_v1_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_v1_graph_proto_goTypes = []any{
	(GraphEventType)(0),                     // 0: goconduct.v1.GraphEventType
	(*GetGraphRequest)(nil),                 // 1: goconduct.v1.GetGraphRequest
	(*GetGraphResponse)(nil),                // 2: goconduct.v1.GetGraphResponse
	(*WatchGraphRequest)(nil),               // 3: goconduct.v1.WatchGraphRequest
	(*WatchGraphResponse)(nil),              // 4: goconduct.v1.WatchGraphResponse
	(*Graph)(nil),                           // 5: goconduct.v1.Graph
	(*AnalysisScope)(nil),                   // 6: goconduct.v1.AnalysisScope
	(*ComponentRules)(nil),                  // 7: goconduct.v1.ComponentRules
	(*ComponentCategoryRule)(nil),           // 8: goconduct.v1.ComponentCategoryRule
	(*AnalysisPolicy)(nil),                  // 9: goconduct.v1.AnalysisPolicy
	(*StableLowAbstractionPolicy)(nil),      // 10: goconduct.v1.StableLowAbstractionPolicy
	(*StableDependencyPrinciplePolicy)(nil), // 11: goconduct.v1.StableDependencyPrinciplePolicy
	(*GraphSummary)(nil),                    // 12: goconduct.v1.GraphSummary
	(*Component)(nil),                       // 13: goconduct.v1.Component
	(*Relationship)(nil),                    // 14: goconduct.v1.Relationship
	(*ImportSite)(nil),                      // 15: goconduct.v1.ImportSite
	(*Function)(nil),                        // 16: goconduct.v1.Function
	(*FunctionCall)(nil),                    // 17: goconduct.v1.FunctionCall
	(*CallSite)(nil),                        // 18: goconduct.v1.CallSite
	(*Cycle)(nil),                           // 19: goconduct.v1.Cycle
	(*Diagnostic)(nil),                      // 20: goconduct.v1.Diagnostic
	(*Finding)(nil),                         // 21: goconduct.v1.Finding
	nil,                                     // 22: goconduct.v1.GraphSummary.CategoriesEntry
	nil,                                     // 23: goconduct.v1.Finding.MetricsEntry
}
var file_v1_graph_proto_depIdxs = []int32{
	5,  // 0: goconduct.v1.GetGraphResponse.graph:type_name -> goconduct.v1.Graph
	0,  // 1: goconduct.v1.WatchGraphResponse.type:type_name -> goconduct.v1.GraphEventType
	6,  // 2: goconduct.v1.Graph.scope:type_name -> goconduct.v1.AnalysisScope
	9,  // 3: goconduct.v1.Graph.policy:type_name -> goconduct.v1.AnalysisPolicy
	12, // 4: goconduct.v1.Graph.summary:type_name -> goconduct.v1.GraphSummary
	13, // 5: goconduct.v1.Graph.components:type_name -> goconduct.v1.Component
	14, // 6: goconduct.v1.Graph.relationships:type_name -> goconduct.v1.Relationship
	16, // 7: goconduct.v1.Graph.functions:type_name -> goconduct.v1.Function
	17, // 8: goconduct.v1.Graph.function_calls:type_name -> goconduct.v1.FunctionCall
	19, // 9: goconduct.v1.Graph.function_cycles:type_name -> goconduct.v1.Cycle
	19, // 10: goconduct.v1.Graph.cycles:type_name -> goconduct.v1.Cycle
	20, // 11: goconduct.v1.Graph.diagnostics:type_name -> goconduct.v1.Diagnostic
	21, // 12: goconduct.v1.Graph.findings:type_name -> goconduct.v1.Finding
	7,  // 13: goconduct.v1.AnalysisScope.components:type_name -> goconduct.v1.ComponentRules
	8,  // 14: goconduct.v1.ComponentRules.taxonomy:type_name -> goconduct.v1.ComponentCategoryRule
	10, // 15: goconduct.v1.AnalysisPolicy.stable_low_abstraction:type_name -> goconduct.v1.StableLowAbstractionPolicy
	11, // 16: goconduct.v1.AnalysisPolicy.stable_dependency_principle:type_name -> goconduct.v1.StableDependencyPrinciplePolicy
	22, // 17: goconduct.v1.GraphSummary.categories:type_name -> goconduct.v1.GraphSummary.CategoriesEntry
	15, // 18: goconduct.v1.Relationship.import_sites:type_name -> goconduct.v1.ImportSite
	18, // 19: goconduct.v1.FunctionCall.call_sites:type_name -> goconduct.v1.CallSite
	23, // 20: goconduct.v1.Finding.metrics:type_name -> goconduct.v1.Finding.MetricsEntry
	1,  // 21: goconduct.v1.GraphService.GetGraph:input_type -> goconduct.v1.GetGraphRequest
	3,  // 22: goconduct.v1.GraphService.WatchGraph:input_type -> goconduct.v1.WatchGraphRequest
	2,  // 23: goconduct.v1.GraphService.GetGraph:output_type -> goconduct.v1.GetGraphResponse
	4,  // 24: goconduct.v1.GraphService.WatchGraph:output_type -> goconduct.v1.WatchGraphResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_v1_graph_proto_init() }
func file_v1_graph_proto_init() {
	if File_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_graph_proto_rawDesc), len(file_v1_graph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_graph_proto_goTypes,
		DependencyIndexes: file_v1_graph_proto_depIdxs,
		EnumInfos:         file_v1_graph_proto_enumTypes,
		MessageInfos:      file_v1_graph_proto_msgTypes,
	}.Build()
	File_v1_graph_proto = out.File
	file_v1_graph_proto_goTypes = nil
	file_v1_graph_proto_depIdxs = nil
}
