// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/quality.proto

package goconductv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindingSeverity int32

const (
	FindingSeverity_FINDING_SEVERITY_UNSPECIFIED FindingSeverity = 0
	FindingSeverity_FINDING_SEVERITY_NOTICE      FindingSeverity = 1
	FindingSeverity_FINDING_SEVERITY_WARNING     FindingSeverity = 2
	FindingSeverity_FINDING_SEVERITY_ERROR       FindingSeverity = 3
)

// Enum value maps for FindingSeverity.
var (
	FindingSeverity_name = map[int32]string{
		0: "FINDING_SEVERITY_UNSPECIFIED",
		1: "FINDING_SEVERITY_NOTICE",
		2: "FINDING_SEVERITY_WARNING",
		3: "FINDING_SEVERITY_ERROR",
	}
	FindingSeverity_value = map[string]int32{
		"FINDING_SEVERITY_UNSPECIFIED": 0,
		"FINDING_SEVERITY_NOTICE":      1,
		"FINDING_SEVERITY_WARNING":     2,
		"FINDING_SEVERITY_ERROR":       3,
	}
)

func (x FindingSeverity) Enum() *FindingSeverity {
	p := new(FindingSeverity)
	*p = x
	return p
}

func (x FindingSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_quality_proto_enumTypes[0].Descriptor()
}

func (FindingSeverity) Type() protoreflect.EnumType {
	return &file_v1_quality_proto_enumTypes[0]
}

func (x FindingSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingSeverity.Descriptor instead.
func (FindingSeverity) EnumDescriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{0}
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_v1_quality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{0}
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginDescriptor    `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_v1_quality_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginDescriptor {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type PluginDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginDescriptor) Reset() {
	*x = PluginDescriptor{}
	mi := &file_v1_quality_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDescriptor) ProtoMessage() {}

func (x *PluginDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDescriptor.ProtoReflect.Descriptor instead.
func (*PluginDescriptor) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{2}
}

func (x *PluginDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RunCheckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryRoot string                 `protobuf:"bytes,1,opt,name=repository_root,json=repositoryRoot,proto3" json:"repository_root,omitempty"`
	Plugins        []string               `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Paths          []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunCheckRequest) Reset() {
	*x = RunCheckRequest{}
	mi := &file_v1_quality_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCheckRequest) ProtoMessage() {}

func (x *RunCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCheckRequest.ProtoReflect.Descriptor instead.
func (*RunCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{3}
}

func (x *RunCheckRequest) GetRepositoryRoot() string {
	if x != nil {
		return x.RepositoryRoot
	}
	return ""
}

func (x *RunCheckRequest) GetPlugins() []string {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *RunCheckRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type RunCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *QualitySummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Reports       []*PluginReport        `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCheckResponse) Reset() {
	*x = RunCheckResponse{}
	mi := &file_v1_quality_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCheckResponse) ProtoMessage() {}

func (x *RunCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCheckResponse.ProtoReflect.Descriptor instead.
func (*RunCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{4}
}

func (x *RunCheckResponse) GetSummary() *QualitySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *RunCheckResponse) GetReports() []*PluginReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type QualitySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       uint32                 `protobuf:"varint,1,opt,name=plugins,proto3" json:"plugins,omitempty"`
	Metrics       uint32                 `protobuf:"varint,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Findings      uint32                 `protobuf:"varint,3,opt,name=findings,proto3" json:"findings,omitempty"`
	Notices       uint32                 `protobuf:"varint,4,opt,name=notices,proto3" json:"notices,omitempty"`
	Warnings      uint32                 `protobuf:"varint,5,opt,name=warnings,proto3" json:"warnings,omitempty"`
	Errors        uint32                 `protobuf:"varint,6,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualitySummary) Reset() {
	*x = QualitySummary{}
	mi := &file_v1_quality_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualitySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualitySummary) ProtoMessage() {}

func (x *QualitySummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualitySummary.ProtoReflect.Descriptor instead.
func (*QualitySummary) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{5}
}

func (x *QualitySummary) GetPlugins() uint32 {
	if x != nil {
		return x.Plugins
	}
	return 0
}

func (x *QualitySummary) GetMetrics() uint32 {
	if x != nil {
		return x.Metrics
	}
	return 0
}

func (x *QualitySummary) GetFindings() uint32 {
	if x != nil {
		return x.Findings
	}
	return 0
}

func (x *QualitySummary) GetNotices() uint32 {
	if x != nil {
		return x.Notices
	}
	return 0
}

func (x *QualitySummary) GetWarnings() uint32 {
	if x != nil {
		return x.Warnings
	}
	return 0
}

func (x *QualitySummary) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type PluginReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Metrics       []*QualityMetric       `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Findings      []*QualityFinding      `protobuf:"bytes,4,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginReport) Reset() {
	*x = PluginReport{}
	mi := &file_v1_quality_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginReport) ProtoMessage() {}

func (x *PluginReport) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginReport.ProtoReflect.Descriptor instead.
func (*PluginReport) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{6}
}

func (x *PluginReport) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PluginReport) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *PluginReport) GetMetrics() []*QualityMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PluginReport) GetFindings() []*QualityFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type QualityMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityMetric) Reset() {
	*x = QualityMetric{}
	mi := &file_v1_quality_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityMetric) ProtoMessage() {}

func (x *QualityMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityMetric.ProtoReflect.Descriptor instead.
func (*QualityMetric) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{7}
}

func (x *QualityMetric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QualityMetric) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QualityMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QualityMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *QualityMetric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type QualityFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Severity      FindingSeverity        `protobuf:"varint,4,opt,name=severity,proto3,enum=goconduct.v1.FindingSeverity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Actual        *float64               `protobuf:"fixed64,6,opt,name=actual,proto3,oneof" json:"actual,omitempty"`
	Limit         *float64               `protobuf:"fixed64,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityFinding) Reset() {
	*x = QualityFinding{}
	mi := &file_v1_quality_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityFinding) ProtoMessage() {}

func (x *QualityFinding) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quality_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityFinding.ProtoReflect.Descriptor instead.
func (*QualityFinding) Descriptor() ([]byte, []int) {
	return file_v1_quality_proto_rawDescGZIP(), []int{8}
}

func (x *QualityFinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QualityFinding) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *QualityFinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QualityFinding) GetSeverity() FindingSeverity {
	if x != nil {
		return x.Severity
	}
	return FindingSeverity_FINDING_SEVERITY_UNSPECIFIED
}

func (x *QualityFinding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QualityFinding) GetActual() float64 {
	if x != nil && x.Actual != nil {
		return *x.Actual
	}
	return 0
}

func (x *QualityFinding) GetLimit() float64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

var File_v1_quality_proto protoreflect.FileDescriptor

const file_v1_quality_proto_rawDesc = "" +
	"\n" +
	"\x10v1/quality.proto\x12\fgoconduct.v1\x1a\x1bbuf/validate/validate.proto\"\x14\n" +
	"\x12ListPluginsRequest\"O\n" +
	"\x13ListPluginsResponse\x128\n" +
	"\aplugins\x18\x01 \x03(\v2\x1e.goconduct.v1.PluginDescriptorR\aplugins\"&\n" +
	"\x10PluginDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc1\x01\n" +
	"\x0fRunCheckRequest\x12A\n" +
	"\x0frepository_root\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x11^$|^[^\\x00\\r\\n]+$R\x0erepositoryRoot\x127\n" +
	"\aplugins\x18\x02 \x03(\tB\x1d\xbaH\x1a\x92\x01\x17\"\x15r\x132\x11^[a-z][a-z0-9-]*$R\aplugins\x122\n" +
	"\x05paths\x18\x03 \x03(\tB\x1c\xbaH\x19\x92\x01\x16\"\x14r\x122\x10^[^\\\\\\x00\\r\\n]+$R\x05paths\"\x80\x01\n" +
	"\x10RunCheckResponse\x126\n" +
	"\asummary\x18\x01 \x01(\v2\x1c.goconduct.v1.QualitySummaryR\asummary\x124\n" +
	"\areports\x18\x02 \x03(\v2\x1a.goconduct.v1.PluginReportR\areports\"\xae\x01\n" +
	"\x0eQualitySummary\x12\x18\n" +
	"\aplugins\x18\x01 \x01(\rR\aplugins\x12\x18\n" +
	"\ametrics\x18\x02 \x01(\rR\ametrics\x12\x1a\n" +
	"\bfindings\x18\x03 \x01(\rR\bfindings\x12\x18\n" +
	"\anotices\x18\x04 \x01(\rR\anotices\x12\x1a\n" +
	"\bwarnings\x18\x05 \x01(\rR\bwarnings\x12\x16\n" +
	"\x06errors\x18\x06 \x01(\rR\x06errors\"\xbe\x01\n" +
	"\fPluginReport\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x125\n" +
	"\ametrics\x18\x03 \x03(\v2\x1b.goconduct.v1.QualityMetricR\ametrics\x128\n" +
	"\bfindings\x18\x04 \x03(\v2\x1c.goconduct.v1.QualityFindingR\bfindings\"q\n" +
	"\rQualityMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\"\xea\x01\n" +
	"\x0eQualityFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x129\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1d.goconduct.v1.FindingSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1b\n" +
	"\x06actual\x18\x06 \x01(\x01H\x00R\x06actual\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\a \x01(\x01H\x01R\x05limit\x88\x01\x01B\t\n" +
	"\a_actualB\b\n" +
	"\x06_limit*\x8a\x01\n" +
	"\x0fFindingSeverity\x12 \n" +
	"\x1cFINDING_SEVERITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FINDING_SEVERITY_NOTICE\x10\x01\x12\x1c\n" +
	"\x18FINDING_SEVERITY_WARNING\x10\x02\x12\x1a\n" +
	"\x16FINDING_SEVERITY_ERROR\x10\x032\xaf\x01\n" +
	"\x0eQualityService\x12R\n" +
	"\vListPlugins\x12 .goconduct.v1.ListPluginsRequest\x1a!.goconduct.v1.ListPluginsResponse\x12I\n" +
	"\bRunCheck\x12\x1d.goconduct.v1.RunCheckRequest\x1a\x1e.goconduct.v1.RunCheckResponseB?Z=github.com/cgardev/goconduct/internal/protogen/v1;goconductv1b\x06proto3"

var (
	file_v1_quality_proto_rawDescOnce sync.Once
	file_v1_quality_proto_rawDescData []byte
)

func file_v1_quality_proto_rawDescGZIP() []byte {
	file_v1_quality_proto_rawDescOnce.Do(func() {
		file_v1_quality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_quality_proto_rawDesc), len(file_v1_quality_proto_rawDesc)))
	})
	return file_v1_quality_proto_rawDescData
}

var file_v1_quality_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_quality_proto_goTypes = []any{
	(FindingSeverity)(0),        // 0: goconduct.v1.FindingSeverity
	(*ListPluginsRequest)(nil),  // 1: goconduct.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil), // 2: goconduct.v1.ListPluginsResponse
	(*PluginDescriptor)(nil),    // 3: goconduct.v1.PluginDescriptor
	(*RunCheckRequest)(nil),     // 4: goconduct.v1.RunCheckRequest
	(*RunCheckResponse)(nil),    // 5: goconduct.v1.RunCheckResponse
	(*QualitySummary)(nil),      // 6: goconduct.v1.QualitySummary
	(*PluginReport)(nil),        // 7: goconduct.v1.PluginReport
	(*QualityMetric)(nil),       // 8: goconduct.v1.QualityMetric
	(*QualityFinding)(nil),      // 9: goconduct.v1.QualityFinding
}
var file_v1_quality_proto_depIdxs = []int32{
	3, // 0: goconduct.v1.ListPluginsResponse.plugins:type_name -> goconduct.v1.PluginDescriptor
	6, // 1: goconduct.v1.RunCheckResponse.summary:type_name -> goconduct.v1.QualitySummary
	7, // 2: goconduct.v1.RunCheckResponse.reports:type_name -> goconduct.v1.PluginReport
	8, // 3: goconduct.v1.PluginReport.metrics:type_name -> goconduct.v1.QualityMetric
	9, // 4: goconduct.v1.PluginReport.findings:type_name -> goconduct.v1.QualityFinding
	0, // 5: goconduct.v1.QualityFinding.severity:type_name -> goconduct.v1.FindingSeverity
	1, // 6: goconduct.v1.QualityService.ListPlugins:input_type -> goconduct.v1.ListPluginsRequest
	4, // 7: goconduct.v1.QualityService.RunCheck:input_type -> goconduct.v1.RunCheckRequest
	2, // 8: goconduct.v1.QualityService.ListPlugins:output_type -> goconduct.v1.ListPluginsResponse
	5, // 9: goconduct.v1.QualityService.RunCheck:output_type -> goconduct.v1.RunCheckResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_quality_proto_init() }
func file_v1_quality_proto_init() {
	if File_v1_quality_proto != nil {
		return
	}
	file_v1_quality_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_quality_proto_rawDesc), len(file_v1_quality_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_quality_proto_goTypes,
		DependencyIndexes: file_v1_quality_proto_depIdxs,
		EnumInfos:         file_v1_quality_proto_enumTypes,
		MessageInfos:      file_v1_quality_proto_msgTypes,
	}.Build()
	File_v1_quality_proto = out.File
	file_v1_quality_proto_goTypes = nil
	file_v1_quality_proto_depIdxs = nil
}
